# Generated by Django 5.2.11 on 2026-07-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ecart_lettrage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte fournisseur',
                'verbose_name_plural': 'Comptes fournisseurs',
                'db_table': 'compta_comptes_fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='CompteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('nature', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit'), ('MIXTE', 'Mixte'), ('NEUTRE', 'Neutre')], max_length=10)),
                ('sens', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit'), ('MIXTE', 'Mixte')], max_length=10)),
                ('niveau', models.IntegerField(default=1)),
                ('type_compte', models.CharField(choices=[('classe', 'Classe'), ('groupe', 'Groupe'), ('compte', 'Compte'), ('sous_compte', 'Sous-compte')], default='compte', max_length=20)),
                ('est_mouvement', models.BooleanField(default=True)),
                ('categorie', models.CharField(choices=[('bilan', 'Bilan'), ('resultat', 'Résultat'), ('hors_bilan', 'Hors bilan')], default='bilan', max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Comptes comptables',
                'db_table': 'compta_comptes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompteTiersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ecart_lettrage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte tiers',
                'verbose_name_plural': 'Comptes tiers',
                'db_table': 'compta_comptes_tiers',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Mon Entreprise', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('nif', models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=50, null=True)),
                ('stat', models.CharField(blank=True, help_text='Numéro Statistique', max_length=50, null=True)),
                ('rccm', models.CharField(blank=True, help_text='Registre de Commerce', max_length=50, null=True)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('exercice_annee', models.CharField(blank=True, max_length=10, null=True)),
                ('est_initialise', models.BooleanField(default=False)),
                ('date_initialisation', models.DateField(blank=True, null=True)),
                ('nombre_comptes', models.IntegerField(default=0)),
                ('situation_initiale_validee', models.BooleanField(default=False)),
                ('date_validation_situation', models.DateTimeField(blank=True, null=True)),
                ('contrepartie_situation', models.CharField(default='101', max_length=20)),
                ('mode_demarrage', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration entreprise',
                'verbose_name_plural': 'Configurations entreprise',
                'db_table': 'compta_configuration_entreprise',
            },
        ),
        migrations.CreateModel(
            name='EcartRapprochement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecart', models.CharField(choices=[('COMMISSION', 'Commission bancaire'), ('INTERET', 'Intérêts'), ('ERREUR', 'Erreur de saisie'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sens', models.CharField(choices=[('CREDIT', 'Crédit (entrée)'), ('DEBIT', 'Débit (sortie)')], max_length=10)),
                ('justification', models.TextField()),
                ('valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compta_ecarts_rapprochement',
            },
        ),
        migrations.CreateModel(
            name='EcritureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date_ecriture', models.DateField()),
                ('libelle', models.TextField()),
                ('piece', models.CharField(blank=True, max_length=50, null=True)),
                ('validee', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'db_table': 'compta_ecritures',
                'ordering': ['-date_ecriture', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cloture', models.BooleanField(default=False)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'verbose_name_plural': 'Exercices comptables',
                'db_table': 'compta_exercices',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('type_immobilisation', models.CharField(choices=[('CORPORELLE', 'Immobilisation corporelle'), ('INCORPORELLE', 'Immobilisation incorporelle'), ('FINANCIERE', 'Immobilisation financière')], max_length=20)),
                ('date_acquisition', models.DateField()),
                ('valeur_originale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valeur_residuelle', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duree_ans', models.IntegerField(help_text="Durée d'amortissement en années")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('CESSION', 'Cédé'), ('SORTIE', 'Sorti')], default='ACTIF', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Immobilisation',
                'verbose_name_plural': 'Immobilisations',
                'db_table': 'compta_immobilisations',
            },
        ),
        migrations.CreateModel(
            name='JournalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_journal', models.CharField(choices=[('ACHATS', 'Achats'), ('VENTES', 'Ventes'), ('BANQUE', 'Banque'), ('CAISSE', 'Caisse'), ('OD', 'Opérations Diverses')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'db_table': 'compta_journaux',
            },
        ),
        migrations.CreateModel(
            name='LigneEcritureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écritures",
                'db_table': 'compta_lignes_ecritures',
            },
        ),
        migrations.CreateModel(
            name='LigneReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sens', models.CharField(choices=[('CREDIT', 'Crédit (entrée)'), ('DEBIT', 'Débit (sortie)')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('NON_RAPPROCHE', 'Non rapproché'), ('RAPPROCHE', 'Rapproché'), ('ECART', 'Écart')], default='NON_RAPPROCHE', max_length=20)),
                ('ecart_justification', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compta_lignes_releve',
                'ordering': ['date_operation'],
            },
        ),
        migrations.CreateModel(
            name='ParametreEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paie', models.CharField(choices=[('SIMPLE', 'Mode simple'), ('AVANCEE', 'Mode avancé')], default='SIMPLE', max_length=20)),
                ('gerer_cnps', models.BooleanField(default=False)),
                ('gerer_impots', models.BooleanField(default=False)),
                ('gerer_avances', models.BooleanField(default=True)),
                ('gerer_stock', models.BooleanField(default=True)),
                ('methode_inventaire', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('PMP', 'PMP')], default='FIFO', max_length=20)),
                ('compte_contrepartie_stock', models.CharField(default='109', help_text="Compte comptable de contrepartie pour l'initialisation du stock (109 = situation initiale par défaut)", max_length=20)),
                ('gerer_tva', models.BooleanField(default=True)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('seuil_alerte_caisse', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres entreprise',
                'verbose_name_plural': 'Paramètres entreprise',
                'db_table': 'compta_parametres_entreprise',
            },
        ),
        migrations.CreateModel(
            name='PlanAmortissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amortissement_cumule', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valeur_nette', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ecriture_generee', models.BooleanField(default=False)),
                ('ecriture_reference', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'compta_plans_amortissement',
                'ordering': ['periode'],
            },
        ),
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('solde_ouverture', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_cloture', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='releves_bancaires/')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('RAPPROCHE', 'Rapproché'), ('CLOTURE', 'Clôturé')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compta_releves_bancaires',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='SoldesInitiaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caisse', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('banque', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stocks', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('clients', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fournisseurs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capital_social', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capital_reel', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reserves', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('report_a_nouveau', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soldes initiaux',
                'verbose_name_plural': 'Soldes initiaux',
                'db_table': 'compta_soldes_initiaux',
            },
        ),
        migrations.CreateModel(
            name='TiersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_tiers', models.CharField(choices=[('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur'), ('PERSONNEL', 'Personnel'), ('ETAT', 'État')], max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('identifiant_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'db_table': 'compta_tiers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ecart_lettrage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='clients.client')),
            ],
            options={
                'verbose_name': 'Compte client',
                'verbose_name_plural': 'Comptes clients',
                'db_table': 'compta_comptes_clients',
            },
        ),
    ]
