# Generated by Django 5.2.13 on 2026-05-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcritureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date_ecriture', models.DateField()),
                ('libelle', models.TextField()),
                ('piece', models.CharField(blank=True, max_length=50, null=True)),
                ('validee', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'db_table': 'compta_ecritures',
                'ordering': ['-date_ecriture', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cloture', models.BooleanField(default=False)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'verbose_name_plural': 'Exercices comptables',
                'db_table': 'compta_exercices',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='JournalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_journal', models.CharField(choices=[('ACHATS', 'Achats'), ('VENTES', 'Ventes'), ('BANQUE', 'Banque'), ('CAISSE', 'Caisse'), ('OD', 'Opérations Diverses')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'db_table': 'compta_journaux',
            },
        ),
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('solde_ouverture', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_cloture', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='releves_bancaires/')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('RAPPROCHE', 'Rapproché'), ('CLOTURE', 'Clôturé')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compta_releves_bancaires',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='TiersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_tiers', models.CharField(choices=[('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur'), ('PERSONNEL', 'Personnel'), ('ETAT', 'État')], max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('identifiant_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'db_table': 'compta_tiers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('nature', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit'), ('MIXTE', 'Mixte'), ('NEUTRE', 'Neutre')], max_length=10)),
                ('sens', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit'), ('MIXTE', 'Mixte')], max_length=10)),
                ('niveau', models.IntegerField(default=1)),
                ('type_compte', models.CharField(choices=[('classe', 'Classe'), ('groupe', 'Groupe'), ('compte', 'Compte'), ('sous_compte', 'Sous-compte')], default='compte', max_length=20)),
                ('est_mouvement', models.BooleanField(default=True)),
                ('categorie', models.CharField(choices=[('bilan', 'Bilan'), ('resultat', 'Résultat'), ('hors_bilan', 'Hors bilan')], default='bilan', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='comptabilite.comptemodel')),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Comptes comptables',
                'db_table': 'compta_comptes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EcartRapprochement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecart', models.CharField(choices=[('COMMISSION', 'Commission bancaire'), ('INTERET', 'Intérêts'), ('ERREUR', 'Erreur de saisie'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sens', models.CharField(choices=[('CREDIT', 'Crédit (entrée)'), ('DEBIT', 'Débit (sortie)')], max_length=10)),
                ('justification', models.TextField()),
                ('valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ecriture_correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.ecrituremodel')),
            ],
            options={
                'db_table': 'compta_ecarts_rapprochement',
            },
        ),
        migrations.AddField(
            model_name='ecrituremodel',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.exercicemodel'),
        ),
        migrations.CreateModel(
            name='CompteTiersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ecart_lettrage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.exercicemodel')),
            ],
            options={
                'verbose_name': 'Compte tiers',
                'verbose_name_plural': 'Comptes tiers',
                'db_table': 'compta_comptes_tiers',
            },
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('type_immobilisation', models.CharField(choices=[('CORPORELLE', 'Immobilisation corporelle'), ('INCORPORELLE', 'Immobilisation incorporelle'), ('FINANCIERE', 'Immobilisation financière')], max_length=20)),
                ('date_acquisition', models.DateField()),
                ('valeur_originale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valeur_residuelle', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duree_ans', models.IntegerField(help_text="Durée d'amortissement en années")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('CESSION', 'Cédé'), ('SORTIE', 'Sorti')], default='ACTIF', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_amortissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amortissements', to='comptabilite.comptemodel')),
                ('compte_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges_amortissement', to='comptabilite.comptemodel')),
                ('compte_immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations', to='comptabilite.comptemodel')),
            ],
            options={
                'verbose_name': 'Immobilisation',
                'verbose_name_plural': 'Immobilisations',
                'db_table': 'compta_immobilisations',
            },
        ),
        migrations.AddField(
            model_name='ecrituremodel',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.journalmodel'),
        ),
        migrations.CreateModel(
            name='LigneEcritureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.comptemodel')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.ecrituremodel')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écritures",
                'db_table': 'compta_lignes_ecritures',
            },
        ),
        migrations.CreateModel(
            name='LigneReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sens', models.CharField(choices=[('CREDIT', 'Crédit (entrée)'), ('DEBIT', 'Débit (sortie)')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('NON_RAPPROCHE', 'Non rapproché'), ('RAPPROCHE', 'Rapproché'), ('ECART', 'Écart')], default='NON_RAPPROCHE', max_length=20)),
                ('ecart_justification', models.TextField(blank=True, null=True)),
                ('ecriture_rapprochee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.ecrituremodel')),
            ],
            options={
                'db_table': 'compta_lignes_releve',
                'ordering': ['date_operation'],
            },
        ),
        migrations.CreateModel(
            name='PlanAmortissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amortissement_cumule', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valeur_nette', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ecriture_generee', models.BooleanField(default=False)),
                ('ecriture_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_amortissement', to='comptabilite.immobilisation')),
            ],
            options={
                'db_table': 'compta_plans_amortissement',
                'ordering': ['periode'],
            },
        ),
    ]
