# Generated by Django 5.2.11 on 2026-07-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='fournisseurs.fournisseur'),
        ),
        migrations.AddField(
            model_name='comptemodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='comptabilite.comptemodel'),
        ),
        migrations.AddField(
            model_name='ecartrapprochement',
            name='ecriture_correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.ecrituremodel'),
        ),
        migrations.AddField(
            model_name='ecrituremodel',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.exercicemodel'),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.exercicemodel'),
        ),
        migrations.AddField(
            model_name='comptetiersmodel',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.exercicemodel'),
        ),
        migrations.AddField(
            model_name='comptefournisseur',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_fournisseurs', to='comptabilite.exercicemodel'),
        ),
        migrations.AddField(
            model_name='compteclient',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_clients', to='comptabilite.exercicemodel'),
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='compte_amortissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amortissements', to='comptabilite.comptemodel'),
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='compte_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges_amortissement', to='comptabilite.comptemodel'),
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='compte_immobilisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations', to='comptabilite.comptemodel'),
        ),
        migrations.AddField(
            model_name='ecrituremodel',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.journalmodel'),
        ),
        migrations.AddField(
            model_name='ligneecrituremodel',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.comptemodel'),
        ),
        migrations.AddField(
            model_name='ligneecrituremodel',
            name='ecriture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.ecrituremodel'),
        ),
        migrations.AddField(
            model_name='lignerelevebancaire',
            name='ecriture_rapprochee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.ecrituremodel'),
        ),
        migrations.AddField(
            model_name='parametreentreprise',
            name='entreprise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='comptabilite.configurationentreprise'),
        ),
        migrations.AddField(
            model_name='planamortissement',
            name='immobilisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_amortissement', to='comptabilite.immobilisation'),
        ),
    ]
