# Generated by Django 5.2.13 on 2026-05-07 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('tresorerie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relevebancaire',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='tresorerie.caisse'),
        ),
        migrations.AddField(
            model_name='relevebancaire',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignerelevebancaire',
            name='releve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.relevebancaire'),
        ),
        migrations.AddField(
            model_name='ecartrapprochement',
            name='releve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecarts', to='comptabilite.relevebancaire'),
        ),
        migrations.AddField(
            model_name='tiersmodel',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiers', to='comptabilite.comptemodel'),
        ),
        migrations.AddField(
            model_name='ligneecrituremodel',
            name='tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptabilite.tiersmodel'),
        ),
        migrations.AddField(
            model_name='comptetiersmodel',
            name='tiers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.tiersmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='planamortissement',
            unique_together={('immobilisation', 'periode')},
        ),
        migrations.AlterUniqueTogether(
            name='comptetiersmodel',
            unique_together={('tiers', 'exercice')},
        ),
    ]
