# Generated by Django 5.2.13 on 2026-05-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Mon Entreprise', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('nif', models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=50, null=True)),
                ('stat', models.CharField(blank=True, help_text='Numéro Statistique', max_length=50, null=True)),
                ('rccm', models.CharField(blank=True, help_text='Registre de Commerce', max_length=50, null=True)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('exercice_annee', models.CharField(blank=True, max_length=10, null=True)),
                ('est_initialise', models.BooleanField(default=False)),
                ('date_initialisation', models.DateField(blank=True, null=True)),
                ('nombre_comptes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.exercicemodel')),
            ],
            options={
                'verbose_name': 'Configuration entreprise',
                'verbose_name_plural': 'Configurations entreprise',
                'db_table': 'compta_configuration_entreprise',
            },
        ),
        migrations.CreateModel(
            name='ParametreEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paie', models.CharField(choices=[('SIMPLE', 'Mode simple'), ('AVANCEE', 'Mode avancé')], default='SIMPLE', max_length=20)),
                ('gerer_cnps', models.BooleanField(default=False)),
                ('gerer_impots', models.BooleanField(default=False)),
                ('gerer_avances', models.BooleanField(default=True)),
                ('gerer_stock', models.BooleanField(default=True)),
                ('methode_inventaire', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('PMP', 'PMP')], default='FIFO', max_length=20)),
                ('gerer_tva', models.BooleanField(default=True)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('seuil_alerte_caisse', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='comptabilite.configurationentreprise')),
            ],
            options={
                'verbose_name': 'Paramètres entreprise',
                'verbose_name_plural': 'Paramètres entreprise',
                'db_table': 'compta_parametres_entreprise',
            },
        ),
        migrations.CreateModel(
            name='SoldesInitiaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caisse', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('banque', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stocks', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('clients', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fournisseurs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capital_social', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capital_reel', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reserves', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('report_a_nouveau', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_initiaux', to='comptabilite.configurationentreprise')),
            ],
            options={
                'verbose_name': 'Soldes initiaux',
                'verbose_name_plural': 'Soldes initiaux',
                'db_table': 'compta_soldes_initiaux',
            },
        ),
    ]
