# Generated by Django 6.0.5 on 2026-05-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_delete_clientmodel_and_more'),
        ('comptabilite', '0003_configurationentreprise_parametreentreprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ecart_lettrage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='clients.client')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_clients', to='comptabilite.exercicemodel')),
            ],
            options={
                'verbose_name': 'Compte client',
                'verbose_name_plural': 'Comptes clients',
                'db_table': 'compta_comptes_clients',
                'unique_together': {('client', 'exercice')},
            },
        ),
    ]
