# Generated by Django 6.0.5 on 2026-05-29 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_compteclient'),
        ('stock', '0008_simplifier_type_mouvement_motif'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ecart_lettrage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_fournisseurs', to='comptabilite.exercicemodel')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='stock.fournisseur')),
            ],
            options={
                'verbose_name': 'Compte fournisseur',
                'verbose_name_plural': 'Comptes fournisseurs',
                'db_table': 'compta_comptes_fournisseurs',
                'unique_together': {('fournisseur', 'exercice')},
            },
        ),
    ]
