# Generated by Django 6.0.5 on 2026-05-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_comptefournisseur'),
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='fournisseurs.fournisseur'),
        ),
    ]
