# Generated by Django 5.2.13 on 2026-06-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_alter_comptefournisseur_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametreentreprise',
            name='compte_contrepartie_stock',
            field=models.CharField(default='109', help_text="Compte comptable de contrepartie pour l'initialisation du stock (109 = situation initiale par défaut)", max_length=20),
        ),
    ]
