# apps/authentication/groups.py
# Constantes partagées pour les noms de groupes Django

PATRON = "PATRON"
MANAGER = "MANAGER"
RECEPTION = "RECEPTION"
CAISSIER = "CAISSIER"
RESTAURANT = "RESTAURANT"
BAR = "BAR"
CUISINE = "CUISINE"
STOCK = "STOCK"
COMPTABLE = "COMPTABLE"
RH = "RH"
TECHNIQUE = "TECHNIQUE"
SECURITE = "SECURITE"
PROMOTEUR = "PROMOTEUR"
RAF = "RAF"

# Regroupements pratiques par domaine
GROUPES_ADMIN = [PATRON, MANAGER, COMPTABLE, RAF]
GROUPES_POS = [BAR, RESTAURANT, CAISSIER, MANAGER, PATRON]
GROUPES_STOCK = [PATRON, MANAGER, STOCK]
GROUPES_BRASSERIE = [PATRON, MANAGER, BAR, CAISSIER]
GROUPES_CATALOGUE = [PATRON, MANAGER, STOCK, BAR, RESTAURANT, CAISSIER]
