# Generated by Django 5.2.13 on 2026-05-07 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=100)),
                ('type_widget', models.CharField(choices=[('OCCUPATION', "Taux d'occupation"), ('CA_JOUR', "Chiffre d'affaires du jour"), ('COMMANDES_EN_COURS', 'Commandes en cours'), ('STOCK_ALERTE', 'Alertes stock'), ('TOP_PLATS', 'Plats les plus commandés'), ('RESERVATIONS', 'Réservations à venir'), ('ACTIVITE_RECENTE', 'Activité récente'), ('CHAMBRES', 'État des chambres')], max_length=30)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('taille', models.CharField(default='md', max_length=10)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'db_table': 'dashboard_widgets',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_interval', models.IntegerField(default=30, help_text='Secondes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_prefs', to=settings.AUTH_USER_MODEL)),
                ('widgets_actifs', models.ManyToManyField(blank=True, to='dashboard.dashboardwidget')),
            ],
            options={
                'verbose_name': 'Préférence dashboard',
                'verbose_name_plural': 'Préférences dashboards',
                'db_table': 'dashboard_user_prefs',
            },
        ),
    ]
