# Generated by Django 6.0.5 on 2026-05-30 17:36
import apps.fournisseurs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0005_comptefournisseur'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Fournisseur',
                    fields=[
                        ('id', models.CharField(default=apps.fournisseurs.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                        ('code', models.CharField(max_length=20, unique=True)),
                        ('nom', models.CharField(max_length=200)),
                        ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('adresse', models.TextField(blank=True, null=True)),
                        ('contact', models.CharField(blank=True, max_length=100, null=True)),
                        ('identifiant_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                        ('notes', models.TextField(blank=True, null=True)),
                        ('actif', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('compte_comptable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs_comptes', to='comptabilite.comptemodel')),
                    ],
                    options={
                        'verbose_name': 'Fournisseur',
                        'verbose_name_plural': 'Fournisseurs',
                        'db_table': 'stock_fournisseurs',
                        'ordering': ['nom'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
