# Generated by Django 5.2.11 on 2026-07-26 19:21

import apps.fournisseurs.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_initial'),
        ('fournisseurs', '0001_initial'),
        ('stock', '0010_politiquestockrestaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheanceFournisseur',
            fields=[
                ('id', models.CharField(default=apps.fournisseurs.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('RETARD', 'En retard'), ('LETTREE', 'Lettrée')], default='ATTENTE', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echeances', to='stock.bonentree')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echeances', to='facturation.facturemodel')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echeances', to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Échéance fournisseur',
                'verbose_name_plural': 'Échéances fournisseurs',
                'db_table': 'fournisseurs_echeances',
                'ordering': ['date_echeance', 'created_at'],
            },
        ),
    ]
