# Generated by Django 5.2.13 on 2026-05-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactureModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('client_id', models.CharField(db_index=True, max_length=50)),
                ('type_facture', models.CharField(choices=[('CHAMBRE', 'Chambre'), ('RESTAURANT', 'Restaurant'), ('BAR', 'Bar'), ('SALLE', 'Salle'), ('SERVICE', 'Service'), ('AVOIR', 'Avoir')], max_length=20)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée'), ('ANNULEE', 'Annulée'), ('EN_RELANCE', 'En relance')], default='EMISE', max_length=20)),
                ('lignes', models.JSONField(default=list)),
                ('paiements', models.JSONField(default=list)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_reservation', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='LigneFactureModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.CharField(choices=[('0', '0%'), ('2.1', '2.1%'), ('5.5', '5.5%'), ('10', '10%'), ('20', '20%')], default='20', max_length=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture', to='facturation.facturemodel')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'db_table': 'factures_lignes',
                'ordering': ['created_at'],
            },
        ),
    ]
