# Generated by Django 5.2.11 on 2026-07-24 09:53

import apps.facturation.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneFactureModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'db_table': 'factures_lignes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactureModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('numero', models.CharField(default=apps.facturation.models.generate_facture_numero, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('CLIENT', 'Facture client'), ('FOURNISSEUR', 'Facture fournisseur')], default='CLIENT', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='factures/')),
                ('client_nom', models.CharField(max_length=200)),
                ('client_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='Contact client')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_entree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='stock.bonentree')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='clients.client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'factures',
                'ordering': ['-date_emission'],
            },
        ),
    ]
