# Generated by Django 5.2.11 on 2026-07-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturation', '0001_initial'),
        ('fournisseurs', '0001_initial'),
        ('hotel', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturemodel',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='pos.commande'),
        ),
        migrations.AddField(
            model_name='facturemodel',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='fournisseurs.fournisseur'),
        ),
        migrations.AddField(
            model_name='facturemodel',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='hotel.locationmodel'),
        ),
        migrations.AddField(
            model_name='facturemodel',
            name='sejour',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='hotel.sejour'),
        ),
        migrations.AddField(
            model_name='lignefacturemodel',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facturemodel'),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['numero'], name='factures_numero_c03f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['statut'], name='factures_statut_d839a2_idx'),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['type'], name='factures_type_99a3df_idx'),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['location'], name='factures_locatio_19cd58_idx'),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['sejour'], name='factures_sejour__8833db_idx'),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['commande'], name='factures_command_dae8eb_idx'),
        ),
    ]
