# Generated by Django 5.2.13 on 2026-05-19 22:31

import apps.facturation.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
        ('hotel', '0003_repair_client_table_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturemodel',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='facturemodel',
            old_name='date_modification',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='facturemodel',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='facturemodel',
            name='date_echeance',
        ),
        migrations.RemoveField(
            model_name='facturemodel',
            name='lignes',
        ),
        migrations.RemoveField(
            model_name='facturemodel',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='facturemodel',
            name='paiements',
        ),
        migrations.RemoveField(
            model_name='facturemodel',
            name='reference_reservation',
        ),
        migrations.RemoveField(
            model_name='facturemodel',
            name='type_facture',
        ),
        migrations.RemoveField(
            model_name='lignefacturemodel',
            name='remise',
        ),
        migrations.RemoveField(
            model_name='lignefacturemodel',
            name='total_ht',
        ),
        migrations.RemoveField(
            model_name='lignefacturemodel',
            name='total_ttc',
        ),
        migrations.RemoveField(
            model_name='lignefacturemodel',
            name='total_tva',
        ),
        migrations.AddField(
            model_name='facturemodel',
            name='client_nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturemodel',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='hotel.locationmodel'),
        ),
        migrations.AlterField(
            model_name='facturemodel',
            name='date_emission',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facturemodel',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facturemodel',
            name='numero',
            field=models.CharField(default=apps.facturation.models.generate_facture_numero, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='facturemodel',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignefacturemodel',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facturemodel'),
        ),
        migrations.AlterField(
            model_name='lignefacturemodel',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lignefacturemodel',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['numero'], name='factures_numero_c03f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['statut'], name='factures_statut_d839a2_idx'),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['location'], name='factures_locatio_19cd58_idx'),
        ),
    ]
