# Generated by Django 5.2.13 on 2026-05-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_rename_date_creation_facturemodel_created_at_and_more'),
        ('hotel', '0005_ajout_commande_facture'),
        ('pos', '0007_ajout_statut_en_cours_de_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturemodel',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='pos.commande'),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['commande'], name='factures_command_dae8eb_idx'),
        ),
    ]
