# Generated by Django 6.0.5 on 2026-05-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_delete_clientmodel_and_more'),
        ('facturation', '0003_ajout_commande_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturemodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='clients.client'),
        ),
    ]
