# Generated by Django 5.2.13 on 2026-06-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_facturemodel_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturemodel',
            name='client_contact',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Contact client'),
        ),
    ]
