# Generated by Django 5.2.13 on 2026-06-09 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rendre_telephone_obligatoire'),
        ('facturation', '0005_facturemodel_client_contact'),
        ('fournisseurs', '0001_initial'),
        ('hotel', '0009_locationmodel_type_tarif_unitemodel_prix_jour'),
        ('pos', '0015_setup_raf_employe'),
        ('stock', '0015_alter_mouvementstock_type_mouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturemodel',
            name='bon_entree',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='stock.bonentree'),
        ),
        migrations.AddField(
            model_name='facturemodel',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='fournisseurs.fournisseur'),
        ),
        migrations.AddField(
            model_name='facturemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='factures/'),
        ),
        migrations.AddField(
            model_name='facturemodel',
            name='type',
            field=models.CharField(choices=[('CLIENT', 'Facture client'), ('FOURNISSEUR', 'Facture fournisseur')], default='CLIENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='facturemodel',
            index=models.Index(fields=['type'], name='factures_type_99a3df_idx'),
        ),
    ]
