# Generated by Django 5.2.13 on 2026-05-07 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
        ('stock', '0001_initial'),
        ('tresorerie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeRestaurantModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type_commande', models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('EMPORTER', 'À emporter'), ('LIVRAISON', 'Livraison'), ('ROOM_SERVICE', 'Room service')], default='SUR_PLACE', max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('client_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('serveur_id', models.CharField(blank=True, max_length=50, null=True)),
                ('serveur_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('SERVI', 'Servi'), ('FACTURE', 'Facturé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande restaurant',
                'verbose_name_plural': 'Commandes restaurant',
                'db_table': 'restaurant_commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAttenteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personnes', models.IntegerField()),
                ('nom_client', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('table_assigned', models.CharField(blank=True, max_length=10, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PLACE', 'Placé'), ('PARTI', 'Parti')], default='EN_ATTENTE', max_length=20)),
            ],
            options={
                'verbose_name': "File d'attente",
                'verbose_name_plural': "Files d'attente",
                'db_table': 'restaurant_file_attente',
                'ordering': ['date_entree'],
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_menu', models.CharField(choices=[('PETIT_DEJEUNER', 'Petit-déjeuner'), ('DEJEUNER', 'Déjeuner'), ('DINER', 'Dîner'), ('ENTREE_PLAT', 'Entrée + Plat'), ('PLAT_DESSERT', 'Plat + Dessert'), ('ENTREE_PLAT_DESSERT', 'Entrée + Plat + Dessert'), ('PLAT_BOISSON', 'Plat + Boisson'), ('MENU_ENFANT', 'Menu enfant'), ('MENU_VEGETARIEN', 'Menu végétarien'), ('MENU_DEGUSTATION', 'Menu dégustation'), ('MENU_SAISON', 'Menu de saison'), ('PROMO_MIDI', 'Promo déjeuner'), ('PROMO_SOIR', 'Promo dîner'), ('PLAT_JOUR', 'Plat du jour'), ('AUTRE', 'Autre')], default='DEJEUNER', max_length=20)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menus/')),
                ('visible_dans_pos', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'restaurant_menus',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit_par', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restaurant_productions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RecetteModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_recette', models.CharField(choices=[('PLAT', 'Plat'), ('BOISSON', 'Boisson'), ('DESSERT', 'Dessert'), ('COCKTAIL', 'Cocktail'), ('PETIT_DEJEUNER', 'Petit-déjeuner'), ('ACCOMPAGNEMENT', 'Accompagnement')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temps_preparation_minutes', models.IntegerField(default=0)),
                ('visible_dans_pos', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recettes/')),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'db_table': 'restaurant_recettes',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('capacite', models.IntegerField()),
                ('statut', models.CharField(choices=[('LIBRE', 'Libre'), ('OCCUPEE', 'Occupée'), ('RESERVEE', 'Réservée'), ('EN_ATTENTE', 'En attente')], default='LIBRE', max_length=20)),
                ('zone', models.CharField(blank=True, help_text='Terrasse, Salon, Bar', max_length=50, null=True)),
                ('serveur_id', models.CharField(blank=True, max_length=50, null=True)),
                ('commande_id', models.CharField(blank=True, max_length=50, null=True)),
                ('heure_arrivee', models.DateTimeField(blank=True, null=True)),
                ('nombre_couverts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'restaurant_tables',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PointDeVenteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caisse', models.OneToOneField(blank=True, help_text='Caisse associée à ce point de vente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_vente_restaurant_associe', to='tresorerie.caisse')),
                ('employes', models.ManyToManyField(blank=True, related_name='points_vente_restaurant', to='rh.employe')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_vente_restaurant', to='stock.entrepot')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='point_vente_restaurant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point de vente restaurant',
                'db_table': 'restaurant_points_vente',
            },
        ),
        migrations.CreateModel(
            name='ProductionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.production')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
            options={
                'db_table': 'restaurant_production_ingredients',
            },
        ),
        migrations.CreateModel(
            name='ProductionLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menumodel')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='restaurant.production')),
            ],
            options={
                'db_table': 'restaurant_production_lignes',
            },
        ),
        migrations.CreateModel(
            name='LigneVenteModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.recettemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LigneMenuModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('groupe', models.CharField(choices=[('ENTREE', 'Entrée'), ('PLAT', 'Plat principal'), ('ACCOMPAGNEMENT', 'Accompagnement'), ('BOISSON', 'Boisson'), ('DESSERT', 'Dessert')], default='PLAT', max_length=20)),
                ('type_ligne', models.CharField(choices=[('FIXE', "Inclus d'office"), ('CHOIX', 'Au choix du client'), ('SUPPLEMENT', 'Supplément payant')], default='FIXE', max_length=20)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_supplement', models.DecimalField(decimal_places=2, default=0, help_text='Si type SUPPLEMENT', max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='restaurant.menumodel')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.recettemodel')),
            ],
            options={
                'verbose_name': 'Ligne de menu',
                'verbose_name_plural': 'Lignes de menu',
                'db_table': 'restaurant_menus_lignes',
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeRestaurantModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock_consomme', models.BooleanField(default=False, help_text='Les ingrédients ont-ils été déduits du stock ?')),
                ('date_consommation', models.DateTimeField(blank=True, help_text='Date de consommation du stock', null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='restaurant.commanderestaurantmodel')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commandes', to='restaurant.menumodel')),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.recettemodel')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'restaurant_lignes_commande',
            },
        ),
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type_ingredient', models.CharField(choices=[('TRACABLE', 'Traçable (stocké)'), ('CONSOMMABLE', 'Consommable (charge globale)')], default='TRACABLE', max_length=20)),
                ('nom', models.CharField(blank=True, help_text='Nom pour les consommables (ex: Sel)', max_length=100, null=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('unite', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('ml', 'Millilitre'), ('piece', 'Pièce'), ('cuillere_cafe', 'Cuillère à café'), ('cuillere_soupe', 'Cuillère à soupe'), ('verre', 'Verre'), ('bouteille', 'Bouteille'), ('pincee', 'Pincée'), ('morceau', 'Morceau'), ('louche', 'Louche'), ('poignee', 'Poignée'), ('unite', 'Unité')], default='piece', max_length=20)),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=2, help_text='Coût unitaire (FCFA)', max_digits=10, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.recettemodel')),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'db_table': 'restaurant_ingredients',
            },
        ),
        migrations.CreateModel(
            name='EtapePreparationModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ordre', models.IntegerField()),
                ('instruction', models.TextField()),
                ('duree_minutes', models.IntegerField(blank=True, null=True)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='restaurant.recettemodel')),
            ],
            options={
                'verbose_name': 'Étape de préparation',
                'verbose_name_plural': 'Étapes de préparation',
                'db_table': 'restaurant_etapes_preparation',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='StockProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_produit', to='restaurant.menumodel')),
            ],
            options={
                'db_table': 'restaurant_stock_produits',
            },
        ),
        migrations.AddField(
            model_name='commanderestaurantmodel',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='restaurant.tablemodel'),
        ),
        migrations.CreateModel(
            name='VenteModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('encaisse_par', models.CharField(max_length=100)),
                ('table_numero', models.CharField(blank=True, max_length=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_restaurant', to='rh.employe')),
                ('lignes', models.ManyToManyField(related_name='ventes', to='restaurant.ligneventemodel')),
                ('point_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='restaurant.pointdeventerestaurant')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'restaurant_ventes',
                'ordering': ['-date_vente'],
            },
        ),
    ]
