# Generated by Django 5.2.11 on 2026-07-24 09:53

import apps.restaurant.models.recette
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttenteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personnes', models.IntegerField()),
                ('nom_client', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('table_assigned', models.CharField(blank=True, max_length=10, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PLACE', 'Placé'), ('PARTI', 'Parti')], default='EN_ATTENTE', max_length=20)),
            ],
            options={
                'verbose_name': "File d'attente",
                'verbose_name_plural': "Files d'attente",
                'db_table': 'restaurant_file_attente',
                'ordering': ['date_entree'],
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_menu', models.CharField(choices=[('FASTFOOD', 'Fast-food'), ('PLAT', 'Plat')], default='PLAT', max_length=20)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menus/')),
                ('visible_dans_pos', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'restaurant_menus',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='RecetteModel',
            fields=[
                ('id', models.CharField(default=apps.restaurant.models.recette.generate_recette_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_recette', models.CharField(choices=[('PLAT', 'Plat'), ('BOISSON', 'Boisson'), ('DESSERT', 'Dessert'), ('COCKTAIL', 'Cocktail'), ('PETIT_DEJEUNER', 'Petit-déjeuner'), ('ACCOMPAGNEMENT', 'Accompagnement')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temps_preparation_minutes', models.IntegerField(default=0)),
                ('visible_dans_pos', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recettes/')),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'db_table': 'restaurant_recettes',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('capacite', models.IntegerField()),
                ('statut', models.CharField(choices=[('LIBRE', 'Libre'), ('OCCUPEE', 'Occupée'), ('RESERVEE', 'Réservée'), ('EN_ATTENTE', 'En attente')], default='LIBRE', max_length=20)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('serveur_id', models.CharField(blank=True, max_length=50, null=True)),
                ('commande_id', models.CharField(blank=True, max_length=50, null=True)),
                ('heure_arrivee', models.DateTimeField(blank=True, null=True)),
                ('nombre_couverts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'restaurant_tables',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_production', models.DateField(blank=True, help_text='Date prévue de production', null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot_dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_entrees', to='stock.entrepot')),
                ('entrepot_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_sorties', to='stock.entrepot')),
                ('produit_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='rh.employe')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_validees', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'db_table': 'restaurant_productions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite', models.CharField(blank=True, max_length=20, null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.production')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
            options={
                'verbose_name': 'Ingrédient consommé',
                'verbose_name_plural': 'Ingrédients consommés',
                'db_table': 'restaurant_production_ingredients',
            },
        ),
        migrations.CreateModel(
            name='ProductionLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menumodel')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='restaurant.production')),
            ],
            options={
                'verbose_name': 'Ligne de production',
                'verbose_name_plural': 'Lignes de production',
                'db_table': 'restaurant_production_lignes',
            },
        ),
        migrations.CreateModel(
            name='LigneMenuModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('groupe', models.CharField(choices=[('ENTREE', 'Entrée'), ('PLAT', 'Plat principal'), ('ACCOMPAGNEMENT', 'Accompagnement'), ('BOISSON', 'Boisson'), ('DESSERT', 'Dessert')], default='PLAT', max_length=20)),
                ('type_ligne', models.CharField(choices=[('FIXE', "Inclus d'office"), ('CHOIX', 'Au choix du client'), ('SUPPLEMENT', 'Supplément payant')], default='FIXE', max_length=20)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_supplement', models.DecimalField(decimal_places=2, default=0, help_text='Si type SUPPLEMENT', max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='restaurant.menumodel')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.recettemodel')),
            ],
            options={
                'verbose_name': 'Ligne de menu',
                'verbose_name_plural': 'Lignes de menu',
                'db_table': 'restaurant_menus_lignes',
            },
        ),
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.CharField(default=apps.restaurant.models.recette.generate_ingredient_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type_ingredient', models.CharField(choices=[('DEDUIRE', 'Déduire du stock'), ('NE_PAS_DEDUIRE', 'Ne pas déduire (charge)')], default='DEDUIRE', max_length=20)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('unite', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('ml', 'Millilitre'), ('piece', 'Pièce'), ('cuillere_cafe', 'Cuillère à café'), ('cuillere_soupe', 'Cuillère à soupe'), ('verre', 'Verre'), ('bouteille', 'Bouteille'), ('pincee', 'Pincée'), ('morceau', 'Morceau'), ('louche', 'Louche'), ('poignee', 'Poignée'), ('unite', 'Unité')], default='piece', max_length=20)),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.recettemodel')),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'db_table': 'restaurant_ingredients',
            },
        ),
        migrations.CreateModel(
            name='EtapePreparationModel',
            fields=[
                ('id', models.CharField(default=apps.restaurant.models.recette.generate_etape_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('ordre', models.IntegerField()),
                ('instruction', models.TextField()),
                ('duree_minutes', models.IntegerField(blank=True, null=True)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='restaurant.recettemodel')),
            ],
            options={
                'verbose_name': 'Étape de préparation',
                'verbose_name_plural': 'Étapes de préparation',
                'db_table': 'restaurant_etapes_preparation',
                'ordering': ['ordre'],
            },
        ),
    ]
