# Generated by Django 5.2.11 on 2026-07-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recettemodel',
            name='produit_fini',
            field=models.ForeignKey(blank=True, help_text='Produit fini obtenu après exécution de la recette', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produit_par_recettes', to='stock.produit'),
        ),
        migrations.AddField(
            model_name='recettemodel',
            name='rendement_quantite',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantité produite par la recette (ex: 50 litres de sauce)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recettemodel',
            name='rendement_unite',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('ml', 'Millilitre'), ('piece', 'Pièce'), ('cuillere_cafe', 'Cuillère à café'), ('cuillere_soupe', 'Cuillère à soupe'), ('verre', 'Verre'), ('bouteille', 'Bouteille'), ('pincee', 'Pincée'), ('morceau', 'Morceau'), ('louche', 'Louche'), ('poignee', 'Poignée'), ('unite', 'Unité')], max_length=20, null=True),
        ),
    ]
