# Generated by Django 5.2.13 on 2026-05-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventemodel',
            name='lignes',
        ),
        migrations.RemoveField(
            model_name='pointdeventerestaurant',
            name='caisse',
        ),
        migrations.RemoveField(
            model_name='pointdeventerestaurant',
            name='employes',
        ),
        migrations.RemoveField(
            model_name='pointdeventerestaurant',
            name='entrepot',
        ),
        migrations.RemoveField(
            model_name='pointdeventerestaurant',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='ventemodel',
            name='point_vente',
        ),
        migrations.RemoveField(
            model_name='ventemodel',
            name='employe',
        ),
        migrations.DeleteModel(
            name='LigneVenteModel',
        ),
        migrations.DeleteModel(
            name='PointDeVenteRestaurant',
        ),
        migrations.DeleteModel(
            name='VenteModel',
        ),
    ]
