# Generated by Django 5.2.13 on 2026-05-11 18:50

import apps.restaurant.models.recette
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_ventemodel_lignes_and_more'),
        ('rh', '0001_initial'),
        ('stock', '0004_inventaire_ligneinventaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-date'], 'verbose_name': 'Production', 'verbose_name_plural': 'Productions'},
        ),
        migrations.AlterModelOptions(
            name='productioningredient',
            options={'verbose_name': 'Ingrédient consommé', 'verbose_name_plural': 'Ingrédients consommés'},
        ),
        migrations.AlterModelOptions(
            name='productionligne',
            options={'verbose_name': 'Ligne de production', 'verbose_name_plural': 'Lignes de production'},
        ),
        migrations.AddField(
            model_name='production',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='date_production',
            field=models.DateField(blank=True, help_text='Date prévue de production', null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='entrepot_dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_entrees', to='stock.entrepot'),
        ),
        migrations.AddField(
            model_name='production',
            name='entrepot_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_sorties', to='stock.entrepot'),
        ),
        migrations.AddField(
            model_name='production',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='production',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20),
        ),
        migrations.AddField(
            model_name='production',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='production',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_validees', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='productioningredient',
            name='unite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etapepreparationmodel',
            name='id',
            field=models.CharField(default=apps.restaurant.models.recette.generate_etape_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='cout_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='id',
            field=models.CharField(default=apps.restaurant.models.recette.generate_ingredient_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='produit_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='rh.employe'),
        ),
        migrations.AlterField(
            model_name='productioningredient',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionligne',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recettemodel',
            name='id',
            field=models.CharField(default=apps.restaurant.models.recette.generate_recette_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='StockProduit',
        ),
    ]
