# Generated by Django 5.2.11 on 2026-07-25 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_recettemodel_produit_fini_and_more'),
        ('stock', '0005_remove_unite_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmodel',
            name='unite_mesure',
            field=models.ForeignKey(blank=True, help_text='Unité de mesure (remplace unite)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredients_recette', to='stock.unitemesure'),
        ),
        migrations.AddField(
            model_name='recettemodel',
            name='rendement_unite_mesure',
            field=models.ForeignKey(blank=True, help_text='Unité de rendement (remplace rendement_unite)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recettes_rendement', to='stock.unitemesure'),
        ),
    ]
