# Generated by Django 5.2.13 on 2026-05-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_production_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommanderestaurantmodel',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='lignecommanderestaurantmodel',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='lignecommanderestaurantmodel',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='lignecommanderestaurantmodel',
            name='recette',
        ),
        migrations.DeleteModel(
            name='CommandeRestaurantModel',
        ),
        migrations.DeleteModel(
            name='LigneCommandeRestaurantModel',
        ),
    ]
