# Generated by Django 5.2.11 on 2026-07-25 06:51

from django.db import migrations

def populate_unites_recettes(apps, schema_editor):
    RecetteModel = apps.get_model('restaurant', 'RecetteModel')
    IngredientModel = apps.get_model('restaurant', 'IngredientModel')
    UniteMesure = apps.get_model('stock', 'UniteMesure')
    
    mapping_unites = {
        'kg': {'nom': 'Kilogramme', 'symbole': 'kg', 'type_unite': 'MASSE', 'unite_reference': True},
        'g': {'nom': 'Gramme', 'symbole': 'g', 'type_unite': 'MASSE', 'unite_reference': False},
        'l': {'nom': 'Litre', 'symbole': 'l', 'type_unite': 'VOLUME', 'unite_reference': True},
        'ml': {'nom': 'Millilitre', 'symbole': 'ml', 'type_unite': 'VOLUME', 'unite_reference': False},
        'piece': {'nom': 'Pièce', 'symbole': 'piece', 'type_unite': 'UNITE', 'unite_reference': True},
        'unite': {'nom': 'Unité', 'symbole': 'unite', 'type_unite': 'UNITE', 'unite_reference': False},
        'cuillere_cafe': {'nom': 'Cuillère à café', 'symbole': 'cac', 'type_unite': 'VOLUME', 'unite_reference': False},
        'cuillere_soupe': {'nom': 'Cuillère à soupe', 'symbole': 'cas', 'type_unite': 'VOLUME', 'unite_reference': False},
        'verre': {'nom': 'Verre', 'symbole': 'verre', 'type_unite': 'VOLUME', 'unite_reference': False},
        'bouteille': {'nom': 'Bouteille', 'symbole': 'bouteille', 'type_unite': 'UNITE', 'unite_reference': False},
        'pincee': {'nom': 'Pincée', 'symbole': 'pincee', 'type_unite': 'MASSE', 'unite_reference': False},
        'morceau': {'nom': 'Morceau', 'symbole': 'morceau', 'type_unite': 'UNITE', 'unite_reference': False},
        'louche': {'nom': 'Louche', 'symbole': 'louche', 'type_unite': 'VOLUME', 'unite_reference': False},
        'poignee': {'nom': 'Poignée', 'symbole': 'poignee', 'type_unite': 'MASSE', 'unite_reference': False},
    }
    
    unites_crees = {}
    for code, data in mapping_unites.items():
        unite, created = UniteMesure.objects.get_or_create(
            symbole=data['symbole'],
            defaults={
                'nom': data['nom'],
                'type_unite': data['type_unite'],
                'unite_reference': data['unite_reference']
            }
        )
        unites_crees[code] = unite
        
    for recette in RecetteModel.objects.all():
        if recette.rendement_unite in unites_crees:
            recette.rendement_unite_mesure = unites_crees[recette.rendement_unite]
            recette.save(update_fields=['rendement_unite_mesure'])

    for ingredient in IngredientModel.objects.all():
        if ingredient.unite in unites_crees:
            ingredient.unite_mesure = unites_crees[ingredient.unite]
            ingredient.save(update_fields=['unite_mesure'])

def backward_populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_ingredientmodel_unite_mesure_and_more'),
        ('stock', '0005_remove_unite_base'),
    ]

    operations = [
        migrations.RunPython(populate_unites_recettes, backward_populate),
    ]
