# Generated by Django 5.2.11 on 2026-07-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_populate_unites_recettes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientmodel',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='recettemodel',
            name='rendement_unite',
        ),
    ]
