# Generated by Django 6.0.5 on 2026-05-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_lignecommanderestaurantmodel_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
