# Generated by Django 6.0.5 on 2026-05-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_tablemodel_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='type_menu',
            field=models.CharField(choices=[('FASTFOOD', 'Fast-food'), ('PLAT', 'Plat')], default='PLAT', max_length=20),
        ),
    ]
