# Generated by Django 5.2.11 on 2026-07-25 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_commande_journee_exploitation_and_more'),
        ('restaurant', '0005_remove_unite_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoixLigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.CharField(choices=[('ENTREE', 'Entrée'), ('PLAT', 'Plat principal'), ('ACCOMPAGNEMENT', 'Accompagnement'), ('BOISSON', 'Boisson'), ('DESSERT', 'Dessert')], max_length=20)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_supplement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix_menu', to='pos.lignecommande')),
                ('ligne_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choix_commandes', to='restaurant.lignemenumodel')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choix_commandes', to='restaurant.recettemodel')),
            ],
            options={
                'verbose_name': 'Choix client (menu)',
                'verbose_name_plural': 'Choix clients (menus)',
                'db_table': 'restaurant_choix_ligne_commande',
            },
        ),
    ]
