# Generated by Django 5.2.11 on 2026-07-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_ajout_choix_ligne_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='choixlignecommande',
            name='cout_unitaire_snapshot',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='choixlignecommande',
            name='nom_recette_snapshot',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
