# Generated by Django 5.2.13 on 2026-06-04 23:27

from django.db import migrations, models


def migrer_type_ingredient(apps, schema_editor):
    IngredientModel = apps.get_model('restaurant', 'IngredientModel')
    IngredientModel.objects.filter(type_ingredient='TRACABLE').update(type_ingredient='DEDUIRE')
    IngredientModel.objects.filter(type_ingredient='CONSOMMABLE').update(type_ingredient='NE_PAS_DEDUIRE')


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_simplify_menu_types'),
    ]

    operations = [
        migrations.RunPython(migrer_type_ingredient, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='type_ingredient',
            field=models.CharField(choices=[('DEDUIRE', 'Déduire du stock'), ('NE_PAS_DEDUIRE', 'Ne pas déduire (charge)')], default='DEDUIRE', max_length=20),
        ),
    ]
