# Generated by Django 5.2.11 on 2026-07-26 17:26

import apps.restaurant.models.version_recette
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_choixlignecommande_cout_unitaire_snapshot_and_more'),
        ('stock', '0010_politiquestockrestaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionRecette',
            fields=[
                ('id', models.CharField(default=apps.restaurant.models.version_recette.generate_version_recette_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('numero_version', models.PositiveIntegerField(help_text='Numéro de version incrémental pour cette recette')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('A_VALIDER', 'À valider'), ('ACTIVE', 'Active'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=20)),
                ('nom_snapshot', models.CharField(max_length=100)),
                ('type_recette_snapshot', models.CharField(max_length=20)),
                ('rendement_quantite_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cree_par', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit_fini_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.produit')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='restaurant.recettemodel')),
            ],
            options={
                'verbose_name': 'Version de recette',
                'verbose_name_plural': 'Versions de recettes',
                'db_table': 'restaurant_version_recette',
                'ordering': ['recette', '-numero_version'],
                'unique_together': {('recette', 'numero_version')},
            },
        ),
    ]
