# Generated by Django 5.2.11 on 2026-07-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_versionrecette'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignemenumodel',
            name='max_choix',
            field=models.IntegerField(default=1, help_text='Nombre maximum de choix autorisés (pour type_ligne=CHOIX)'),
        ),
        migrations.AddField(
            model_name='lignemenumodel',
            name='min_choix',
            field=models.IntegerField(default=0, help_text='Nombre minimum de choix requis (pour type_ligne=CHOIX)'),
        ),
    ]
