# Generated by Django 5.2.11 on 2026-07-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_lignemenumodel_max_choix_lignemenumodel_min_choix'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioningredient',
            name='cout_unitaire',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Coût unitaire au moment de la consommation', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productioningredient',
            name='ligne',
            field=models.ForeignKey(blank=True, help_text='Ligne de production à laquelle cet ingrédient est attribué', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.productionligne'),
        ),
        migrations.AddField(
            model_name='productionligne',
            name='cout_reel_ligne',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coût réel des ingrédients consommés pour cette ligne', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='productionligne',
            name='quantite_reelle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantité réellement produite (remplie après production)', max_digits=10, null=True),
        ),
    ]
