# Generated by Django 5.2.11 on 2026-07-24 09:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('fournisseurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, default='', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
                'db_table': 'stock_domaines',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_entrepot', models.CharField(choices=[('CENTRAL', 'Magasin Central'), ('BAR', 'Bar'), ('BRASSERIE', 'Brasserie'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hôtel'), ('CUISINE', 'Cuisine'), ('SPA', 'Spa'), ('MINIBAR', 'Mini-bar')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'db_table': 'stock_entrepots',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.categorieproduit')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'stock_categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='BonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name="Numéro bon d'entrée")),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Réf. fournisseur (facture)')),
                ('date_commande', models.DateField(blank=True, null=True, verbose_name='Date commande')),
                ('date_reception', models.DateField(auto_now_add=True, verbose_name='Date réception')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('transporteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transporteur')),
                ('numero_bl', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Bon de livraison')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PARTIEL', 'Partiellement réceptionné'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valide_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree', to='fournisseurs.fournisseur', verbose_name='Fournisseur')),
                ('valide_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree', to='stock.entrepot', verbose_name='Entrepôt destination')),
            ],
            options={
                'verbose_name': "Bon d'entrée",
                'verbose_name_plural': "Bons d'entrée",
                'db_table': 'stock_bons_entree',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=20)),
                ('realise_par', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='stock.entrepot')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'db_table': 'stock_inventaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('code_barre', models.CharField(blank=True, help_text='Code-barres EAN-13 / Code produit', max_length=100, null=True, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_article', models.CharField(choices=[('MARCHANDISE', 'Marchandise'), ('MATIERE_PREMIERE', 'Matière première'), ('EMBALLAGE', 'Emballage'), ('CONSOMMABLE', 'Consommable interne'), ('IMMOBILISATION', 'Immobilisation'), ('SERVICE', 'Service')], default='MARCHANDISE', max_length=30)),
                ('est_vendable', models.BooleanField(default=False, verbose_name='Visible dans le catalogue')),
                ('unite_base', models.CharField(choices=[('piece', 'Pièce'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('cl', 'Centilitre'), ('botte', 'Botte'), ('sachet', 'Sachet'), ('boite', 'Boîte'), ('caisse', 'Caisse')], default='piece', max_length=20)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('budget_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stock/produits/')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.categorieproduit')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.domaine')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'stock_produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('INITIALISATION', 'Initialisation')], default='ENTREE', max_length=20)),
                ('motif', models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente'), ('consommation', 'Consommation'), ('perte', 'Perte'), ('production', 'Production'), ('reapprovisionnement', 'Réapprovisionnement'), ('inventaire', 'Inventaire'), ('stock_initial', 'Stock initial')], default='achat', max_length=30)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valeur_unitaire', models.DecimalField(decimal_places=2, default=0, help_text='Prix unitaire au moment du mouvement', max_digits=10)),
                ('valeur_total', models.DecimalField(decimal_places=2, default=0, help_text='Quantite x valeur unitaire', max_digits=15)),
                ('reference', models.CharField(blank=True, help_text='Reference de la piece source (CMD-00045, FACT-001, etc.)', max_length=100, null=True)),
                ('raison', models.CharField(blank=True, max_length=200)),
                ('utilisateur', models.CharField(max_length=100)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('unite_texte', models.CharField(blank=True, max_length=100, null=True)),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='comptabilite.ecrituremodel')),
                ('entrepot_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_dest', to='stock.entrepot')),
                ('entrepot_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_source', to='stock.entrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'stock_mouvements',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numéro du lot', max_length=50)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantite_restante', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fournisseurs.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'stock_lots',
                'ordering': ['date_peremption', '-date_entree'],
                'unique_together': {('produit', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='LigneBonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité commandée')),
                ('quantite_recue', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité reçue')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'achat unitaire")),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('bon_entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.bonentree', verbose_name="Bon d'entrée")),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bon_entree', to='stock.lot', verbose_name='Lot associé')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bon_entree', to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Ligne de bon d'entrée",
                'verbose_name_plural': "Lignes de bons d'entrée",
                'db_table': 'stock_bons_entree_lignes',
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantite_reelle', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Prix d'achat unitaire")),
                ('ecart', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
            options={
                'db_table': 'stock_inventaires_lignes',
                'unique_together': {('inventaire', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='SousUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Caisse, Pack, Carton', max_length=50)),
                ('facteur', models.DecimalField(decimal_places=2, help_text="Nombre d'unités dans cette sous-unité", max_digits=10)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, help_text='Prix spécifique (optionnel)', max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_unites', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Sous-unité',
                'verbose_name_plural': 'Sous-unités',
                'db_table': 'stock_sous_unites',
                'ordering': ['produit__nom', 'nom'],
                'unique_together': {('produit', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='StockEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Prix d'achat unitaire")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.entrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_entrepots', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Stock entrepôt',
                'verbose_name_plural': 'Stocks entrepôts',
                'db_table': 'stock_entrepots_stock',
                'unique_together': {('entrepot', 'produit')},
            },
        ),
    ]
