# Generated by Django 5.2.13 on 2026-05-07 14:57

import apps.stock.models.fournisseur
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_entrepot', models.CharField(choices=[('CENTRAL', 'Magasin Central'), ('BAR', 'Bar'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'HÃ´tel'), ('CUISINE', 'Cuisine'), ('SPA', 'Spa'), ('MINIBAR', 'Mini-bar')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'EntrepÃ´t',
                'verbose_name_plural': 'EntrepÃ´ts',
                'db_table': 'stock_entrepots',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.CharField(default=apps.stock.models.fournisseur.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'stock_fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.categorieproduit')),
            ],
            options={
                'verbose_name': 'CatÃ©gorie',
                'verbose_name_plural': 'CatÃ©gories',
                'db_table': 'stock_categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('code_barre', models.CharField(blank=True, help_text='Code-barres EAN-13 / Code produit', max_length=100, null=True, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_gestion', models.CharField(choices=[('TRACABLE', 'TraÃ§able (comptage unitaire)'), ('CONSOMMABLE', 'Consommable (gestion par dÃ©pense)')], default='TRACABLE', max_length=20)),
                ('unite_base', models.CharField(choices=[('piece', 'PiÃ¨ce'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('cl', 'Centilitre'), ('botte', 'Botte'), ('sachet', 'Sachet'), ('boite', 'BoÃ®te'), ('caisse', 'Caisse')], default='piece', max_length=20)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('budget_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stock/produits/')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.categorieproduit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'stock_produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('ENTREE', 'EntrÃ©e (rÃ©ception)'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert entre entrepÃ´ts'), ('CASSE', 'Casse / Perte'), ('INVENTAIRE', 'Ajustement inventaire')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('raison', models.CharField(blank=True, max_length=200)),
                ('utilisateur', models.CharField(max_length=100)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('unite_texte', models.CharField(blank=True, max_length=100, null=True)),
                ('entrepot_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_dest', to='stock.entrepot')),
                ('entrepot_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_source', to='stock.entrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.produit')),
            ],
            options={
                'db_table': 'stock_mouvements',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='NumÃ©ro du lot', max_length=50)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantite_restante', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'stock_lots',
                'ordering': ['date_peremption', '-date_entree'],
                'unique_together': {('produit', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='SousUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Caisse, Pack, Carton', max_length=50)),
                ('facteur', models.DecimalField(decimal_places=2, help_text="Nombre d'unitÃ©s dans cette sous-unitÃ©", max_digits=10)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, help_text='Prix spÃ©cifique (optionnel)', max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_unites', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Sous-unitÃ©',
                'verbose_name_plural': 'Sous-unitÃ©s',
                'db_table': 'stock_sous_unites',
                'ordering': ['produit__nom', 'nom'],
                'unique_together': {('produit', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='StockEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.entrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_entrepots', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Stock entrepÃ´t',
                'verbose_name_plural': 'Stocks entrepÃ´ts',
                'db_table': 'stock_entrepots_stock',
                'unique_together': {('entrepot', 'produit')},
            },
        ),
    ]

