# Generated by Django 5.2.13 on 2026-05-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='type_article',
            field=models.CharField(choices=[('MATIERE_PREMIERE', 'MatiÃ¨re premiÃ¨re'), ('MARCHANDISE', 'Marchandise')], default='MARCHANDISE', max_length=30),
        ),
    ]

