# Generated by Django 5.2.11 on 2026-07-24 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='methode_valorisation',
            field=models.CharField(choices=[('CUMP', 'Coût moyen pondéré'), ('FIFO', 'Premier entré, premier sorti'), ('STANDARD', 'Coût standard')], default='CUMP', max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='motif',
            field=models.CharField(choices=[('ACHAT', 'Achat'), ('VENTE', 'Vente'), ('PRODUCTION', 'Production'), ('CONSOMMATION', 'Consommation'), ('PERTE', 'Perte'), ('INVENTAIRE', 'Inventaire'), ('TRANSFERT', 'Transfert'), ('RETOUR', 'Retour'), ('ANNULATION', 'Annulation'), ('INITIALISATION', 'Initialisation')], default='ACHAT', max_length=30),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT_ENTREE', 'Entrée transfert'), ('TRANSFERT_SORTIE', 'Sortie transfert'), ('AJUSTEMENT_POSITIF', 'Ajustement positif'), ('AJUSTEMENT_NEGATIF', 'Ajustement négatif'), ('INITIALISATION', 'Initialisation')], default='ENTREE', max_length=20),
        ),
        migrations.CreateModel(
            name='SourceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_source', models.CharField(choices=[('ACHAT', 'Achat'), ('VENTE', 'Vente'), ('PRODUCTION', 'Production'), ('CONSOMMATION', 'Consommation'), ('PERTE', 'Perte'), ('INVENTAIRE', 'Inventaire'), ('TRANSFERT', 'Transfert'), ('RETOUR', 'Retour'), ('ANNULATION', 'Annulation'), ('INITIALISATION', 'Initialisation')], max_length=30)),
                ('reference', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': "Source d'opération",
                'verbose_name_plural': "Sources d'opérations",
                'db_table': 'stock_source_operations',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='source_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.sourceoperation'),
        ),
        migrations.CreateModel(
            name='JournalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_avant', models.DecimalField(decimal_places=4, max_digits=18)),
                ('quantite_mouvement', models.DecimalField(decimal_places=4, max_digits=18)),
                ('stock_apres', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cout_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valeur_mouvement', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('effectue_par', models.CharField(blank=True, max_length=100, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('effectue_par_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique_journal', to='stock.entrepot')),
                ('mouvement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to='stock.mouvementstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique_journal', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Entrée au journal de stock',
                'verbose_name_plural': 'Journal de stock',
                'db_table': 'stock_journal',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['produit', 'entrepot', '-cree_le'], name='stock_journ_produit_486deb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sourceoperation',
            index=models.Index(fields=['type_source'], name='stock_sourc_type_so_1f59f8_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceoperation',
            index=models.Index(fields=['reference'], name='stock_sourc_referen_4be76f_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceoperation',
            index=models.Index(fields=['content_type', 'object_id'], name='stock_sourc_content_18b0b8_idx'),
        ),
    ]
