# Generated by Django 5.2.11 on 2026-07-25 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_produit_methode_valorisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Kilogramme, Litre, Pièce', max_length=50, unique=True)),
                ('symbole', models.CharField(help_text='Ex: kg, l, pce', max_length=10, unique=True)),
                ('type_unite', models.CharField(choices=[('MASSE', 'Masse (Kg, g...)'), ('VOLUME', 'Volume (L, cl...)'), ('UNITE', 'Unité (Pièce, Unité)'), ('LONGUEUR', 'Longueur (m, cm...)')], default='UNITE', max_length=20)),
                ('unite_reference', models.BooleanField(default=False, help_text="Cocher si c'est l'unité de référence pour ce type (ex: Kg pour la Masse)")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'db_table': 'stock_unite_mesure',
                'ordering': ['type_unite', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_mesure',
            field=models.ForeignKey(blank=True, help_text='Unité de mesure standard pour ce produit (remplace unite_base)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='stock.unitemesure'),
        ),
        migrations.CreateModel(
            name='ConversionUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facteur', models.DecimalField(decimal_places=6, help_text="Combien d'unités source faut-il pour 1 unité de destination ? (ex: Source=Kg, Dest=g, Facteur=1000)", max_digits=18)),
                ('unite_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_dest', to='stock.unitemesure')),
                ('unite_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_source', to='stock.unitemesure')),
            ],
            options={
                'verbose_name': "Conversion d'unité",
                'verbose_name_plural': "Conversions d'unités",
                'db_table': 'stock_conversion_unite',
                'unique_together': {('unite_source', 'unite_dest')},
            },
        ),
        migrations.CreateModel(
            name='Conditionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Caisse, Carton, Palette', max_length=100)),
                ('facteur', models.DecimalField(decimal_places=6, help_text="Nombre d'unités de destination dans ce conditionnement (ex: 1 Caisse = 24 Pièces -> Facteur=24)", max_digits=18)),
                ('code_barre', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionnements', to='stock.produit')),
                ('unite_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.unitemesure')),
            ],
            options={
                'verbose_name': 'Conditionnement',
                'verbose_name_plural': 'Conditionnements',
                'db_table': 'stock_conditionnement',
                'unique_together': {('produit', 'nom')},
            },
        ),
    ]
