# Generated by Django 5.2.13 on 2026-05-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_produit_type_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type_article',
            field=models.CharField(choices=[('MARCHANDISE', 'Marchandise'), ('MATIERE_PREMIERE', 'MatiÃ¨re premiÃ¨re'), ('CONSOMMABLE', 'Consommable interne'), ('IMMOBILISATION', 'Immobilisation')], default='MARCHANDISE', max_length=30),
        ),
    ]

