# Generated by Django 5.2.11 on 2026-07-25 06:13

from django.db import migrations

def populate_unites(apps, schema_editor):
    Produit = apps.get_model('stock', 'Produit')
    UniteMesure = apps.get_model('stock', 'UniteMesure')
    
    mapping_unites = {
        'piece': {'nom': 'Pièce', 'symbole': 'piece', 'type_unite': 'UNITE', 'unite_reference': True},
        'kg': {'nom': 'Kilogramme', 'symbole': 'kg', 'type_unite': 'MASSE', 'unite_reference': True},
        'g': {'nom': 'Gramme', 'symbole': 'g', 'type_unite': 'MASSE', 'unite_reference': False},
        'l': {'nom': 'Litre', 'symbole': 'l', 'type_unite': 'VOLUME', 'unite_reference': True},
        'cl': {'nom': 'Centilitre', 'symbole': 'cl', 'type_unite': 'VOLUME', 'unite_reference': False},
        'botte': {'nom': 'Botte', 'symbole': 'botte', 'type_unite': 'UNITE', 'unite_reference': False},
        'sachet': {'nom': 'Sachet', 'symbole': 'sachet', 'type_unite': 'UNITE', 'unite_reference': False},
        'boite': {'nom': 'Boîte', 'symbole': 'boite', 'type_unite': 'UNITE', 'unite_reference': False},
        'caisse': {'nom': 'Caisse', 'symbole': 'caisse', 'type_unite': 'UNITE', 'unite_reference': False},
    }
    
    unites_crees = {}
    for code, data in mapping_unites.items():
        unite, created = UniteMesure.objects.get_or_create(
            symbole=data['symbole'],
            defaults={
                'nom': data['nom'],
                'type_unite': data['type_unite'],
                'unite_reference': data['unite_reference']
            }
        )
        unites_crees[code] = unite
        
    for produit in Produit.objects.all():
        if produit.unite_base in unites_crees:
            produit.unite_mesure = unites_crees[produit.unite_base]
            produit.save(update_fields=['unite_mesure'])

def backward_populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_unitemesure_produit_unite_mesure_conversionunite_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_unites, backward_populate),
    ]
