# Generated by Django 5.2.13 on 2026-05-09 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_produit_type_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('TERMINE', 'TerminÃ©'), ('VALIDE', 'ValidÃ©')], default='BROUILLON', max_length=20)),
                ('realise_par', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='stock.entrepot')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'db_table': 'stock_inventaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantite_reelle', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ecart', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
            options={
                'db_table': 'stock_inventaires_lignes',
                'unique_together': {('inventaire', 'produit')},
            },
        ),
    ]

