# Generated by Django 5.2.11 on 2026-07-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_populate_unite_mesure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='unite_base',
        ),
    ]
