# Generated by Django 5.2.13 on 2026-05-23 11:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_inventaire_ligneinventaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name="NumÃ©ro bon d'entrÃ©e")),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, null=True, verbose_name='RÃ©f. fournisseur (facture)')),
                ('date_commande', models.DateField(blank=True, null=True, verbose_name='Date commande')),
                ('date_reception', models.DateField(auto_now_add=True, verbose_name='Date rÃ©ception')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('transporteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transporteur')),
                ('numero_bl', models.CharField(blank=True, max_length=100, null=True, verbose_name='NÂ° Bon de livraison')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'ValidÃ©'), ('PARTIEL', 'Partiellement rÃ©ceptionnÃ©'), ('ANNULE', 'AnnulÃ©')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valide_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree_crees', to=settings.AUTH_USER_MODEL, verbose_name='CrÃ©Ã© par')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree', to='stock.entrepot', verbose_name='EntrepÃ´t destination')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree', to='stock.fournisseur', verbose_name='Fournisseur')),
                ('valide_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree_valides', to=settings.AUTH_USER_MODEL, verbose_name='ValidÃ© par')),
            ],
            options={
                'verbose_name': "Bon d'entrÃ©e",
                'verbose_name_plural': "Bons d'entrÃ©e",
                'db_table': 'stock_bons_entree',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='QuantitÃ© commandÃ©e')),
                ('quantite_recue', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='QuantitÃ© reÃ§ue')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'achat unitaire HT")),
                ('tva', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='TVA (%)')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant HT')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TTC')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de pÃ©remption')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('bon_entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.bonentree', verbose_name="Bon d'entrÃ©e")),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bon_entree', to='stock.lot', verbose_name='Lot associÃ©')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bon_entree', to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Ligne de bon d'entrÃ©e",
                'verbose_name_plural': "Lignes de bons d'entrÃ©e",
                'db_table': 'stock_bons_entree_lignes',
            },
        ),
    ]

