# Generated by Django 5.2.11 on 2026-07-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_unite_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionunite',
            name='facteur',
            field=models.DecimalField(decimal_places=6, help_text='Quantité de destination obtenue pour 1 unité source. (ex: Source=Kg, Dest=g, Facteur=1000)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.produit'),
        ),
    ]
