# Generated by Django 5.2.11 on 2026-07-25 11:59

import apps.stock.models.transfert
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_conversionunite_facteur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('numero', models.CharField(default=apps.stock.models.transfert.generate_transfert_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_crees', to=settings.AUTH_USER_MODEL)),
                ('entrepot_dest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='stock.entrepot')),
                ('entrepot_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='stock.entrepot')),
                ('source_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.sourceoperation')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'db_table': 'stock_transfert',
            },
        ),
        migrations.CreateModel(
            name='LigneTransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=4, max_digits=18)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
                ('unite_mesure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.unitemesure')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.transfertstock')),
            ],
            options={
                'verbose_name': 'Ligne de transfert',
                'verbose_name_plural': 'Lignes de transfert',
                'db_table': 'stock_ligne_transfert',
            },
        ),
    ]
