# Generated by Django 5.2.13 on 2026-05-24 13:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_configurationentreprise_parametreentreprise_and_more'),
        ('stock', '0006_ajout_domaine_produit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonentree',
            options={'ordering': ['-date_reception'], 'verbose_name': "Bon d'entrée", 'verbose_name_plural': "Bons d'entrée"},
        ),
        migrations.AlterModelOptions(
            name='categorieproduit',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='entrepot',
            options={'ordering': ['nom'], 'verbose_name': 'Entrepôt', 'verbose_name_plural': 'Entrepôts'},
        ),
        migrations.AlterModelOptions(
            name='lignebonentree',
            options={'verbose_name': "Ligne de bon d'entrée", 'verbose_name_plural': "Lignes de bons d'entrée"},
        ),
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'ordering': ['-date_mouvement'], 'verbose_name': 'Mouvement de stock', 'verbose_name_plural': 'Mouvements de stock'},
        ),
        migrations.AlterModelOptions(
            name='sousunite',
            options={'ordering': ['produit__nom', 'nom'], 'verbose_name': 'Sous-unité', 'verbose_name_plural': 'Sous-unités'},
        ),
        migrations.AlterModelOptions(
            name='stockentrepot',
            options={'verbose_name': 'Stock entrepôt', 'verbose_name_plural': 'Stocks entrepôts'},
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='ecriture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='comptabilite.ecrituremodel'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='sens',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('NEUTRE', 'Neutre (transfert)')], default='ENTREE', max_length=10),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='valeur_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantite x valeur unitaire', max_digits=15),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='valeur_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix unitaire au moment du mouvement', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bonentree',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='bonentree',
            name='date_reception',
            field=models.DateField(auto_now_add=True, verbose_name='Date réception'),
        ),
        migrations.AlterField(
            model_name='bonentree',
            name='entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree', to='stock.entrepot', verbose_name='Entrepôt destination'),
        ),
        migrations.AlterField(
            model_name='bonentree',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name="Numéro bon d'entrée"),
        ),
        migrations.AlterField(
            model_name='bonentree',
            name='numero_bl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Bon de livraison'),
        ),
        migrations.AlterField(
            model_name='bonentree',
            name='reference_fournisseur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Réf. fournisseur (facture)'),
        ),
        migrations.AlterField(
            model_name='bonentree',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PARTIEL', 'Partiellement réceptionné'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='bonentree',
            name='valide_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='type_entrepot',
            field=models.CharField(choices=[('CENTRAL', 'Magasin Central'), ('BAR', 'Bar'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hôtel'), ('CUISINE', 'Cuisine'), ('SPA', 'Spa'), ('MINIBAR', 'Mini-bar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignebonentree',
            name='bon_entree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.bonentree', verbose_name="Bon d'entrée"),
        ),
        migrations.AlterField(
            model_name='lignebonentree',
            name='date_peremption',
            field=models.DateField(blank=True, null=True, verbose_name='Date de péremption'),
        ),
        migrations.AlterField(
            model_name='lignebonentree',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bon_entree', to='stock.lot', verbose_name='Lot associé'),
        ),
        migrations.AlterField(
            model_name='lignebonentree',
            name='quantite_commandee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité commandée'),
        ),
        migrations.AlterField(
            model_name='lignebonentree',
            name='quantite_recue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité reçue'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='numero',
            field=models.CharField(help_text='Numéro du lot', max_length=50),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_operation',
            field=models.CharField(choices=[('ACHAT', 'Achat fournisseur'), ('VENTE', 'Vente client'), ('RETOUR_CLIENT', 'Retour client'), ('RETOUR_FOURNISSEUR', 'Retour fournisseur'), ('PRODUCTION', 'Production / Transformation'), ('TRANSFERT', 'Transfert entre entrepôts'), ('PEREMPTION', 'Péremption'), ('CASSE', 'Casse / Perte / Vol'), ('CONSOMMATION', 'Consommation interne'), ('DON', 'Don offert'), ('DON_RECU', 'Don reçu'), ('CORRECTION_INVENTAIRE', 'Correction inventaire'), ('INVENTAIRE_INITIAL', 'Stock initial')], default='ACHAT', max_length=30),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type_article',
            field=models.CharField(choices=[('MARCHANDISE', 'Marchandise'), ('MATIERE_PREMIERE', 'Matière première'), ('CONSOMMABLE', 'Consommable interne'), ('IMMOBILISATION', 'Immobilisation')], default='MARCHANDISE', max_length=30),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type_gestion',
            field=models.CharField(choices=[('TRACABLE', 'Traçable (comptage unitaire)'), ('CONSOMMABLE', 'Consommable (gestion par dépense)')], default='TRACABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite_base',
            field=models.CharField(choices=[('piece', 'Pièce'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('cl', 'Centilitre'), ('botte', 'Botte'), ('sachet', 'Sachet'), ('boite', 'Boîte'), ('caisse', 'Caisse')], default='piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='sousunite',
            name='facteur',
            field=models.DecimalField(decimal_places=2, help_text="Nombre d'unités dans cette sous-unité", max_digits=10),
        ),
        migrations.AlterField(
            model_name='sousunite',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix spécifique (optionnel)', max_digits=10, null=True),
        ),
    ]
