# Generated by Django 5.2.11 on 2026-07-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('stock', '0007_transfertstock_lignetransfertstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numéro du lot', max_length=50)),
                ('date_fabrication', models.DateField(blank=True, null=True)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fournisseurs.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_produit', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Lot Produit',
                'verbose_name_plural': 'Lots Produits',
                'db_table': 'stock_lot_produit',
                'ordering': ['date_peremption', '-date_creation'],
                'unique_together': {('produit', 'numero')},
            },
        ),
        migrations.AlterField(
            model_name='lignebonentree',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bon_entree', to='stock.lotproduit', verbose_name='Lot associé'),
        ),
        migrations.CreateModel(
            name='MouvementLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=4, max_digits=18)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.lotproduit')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_lots', to='stock.mouvementstock')),
            ],
            options={
                'verbose_name': 'Mouvement de Lot',
                'verbose_name_plural': 'Mouvements de Lots',
                'db_table': 'stock_mouvement_lot',
            },
        ),
        migrations.CreateModel(
            name='StockLotEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_lots', to='stock.entrepot')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_entrepot', to='stock.lotproduit')),
            ],
            options={
                'verbose_name': 'Stock Lot Entrepôt',
                'verbose_name_plural': 'Stocks Lots Entrepôts',
                'db_table': 'stock_stock_lot_entrepot',
                'unique_together': {('lot', 'entrepot')},
            },
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
