# Generated by Django 5.2.11 on 2026-07-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_lotproduit_alter_lignebonentree_lot_mouvementlot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignetransfertstock',
            name='transfert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='stock.transfertstock'),
        ),
        migrations.AlterField(
            model_name='mouvementlot',
            name='mouvement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_lots', to='stock.mouvementstock'),
        ),
        migrations.AlterField(
            model_name='mouvementlot',
            name='quantite',
            field=models.DecimalField(decimal_places=4, help_text='Quantité signée : positive pour une entrée, négative pour une sortie.', max_digits=18),
        ),
        migrations.AddConstraint(
            model_name='mouvementlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantite', 0), _negated=True), name='mouvement_lot_quantite_non_nulle'),
        ),
    ]
