# Generated by Django 6.0.5 on 2026-05-29 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_comptefournisseur'),
        ('stock', '0008_simplifier_type_mouvement_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='compte_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs', to='comptabilite.comptemodel'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='identifiant_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
