# Generated by Django 5.2.11 on 2026-07-26 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('pos', '0006_commande_journee_exploitation_and_more'),
        ('stock', '0009_alter_lignetransfertstock_transfert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolitiqueStockRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_consommation', models.CharField(choices=[('AUTO', 'Automatique'), ('MANUEL', 'Manuel'), ('DIFFERE', 'Différé')], default='AUTO', help_text='Quand la consommation est-elle déclenchée', max_length=10)),
                ('evenement_declencheur', models.CharField(choices=[('PAIEMENT', 'Au paiement'), ('VALIDATION', 'À la validation de commande'), ('CLOTURE', 'À la clôture de caisse'), ('MANUEL', 'Déclenchement manuel')], default='PAIEMENT', help_text='Événement qui déclenche la consommation', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot_source', models.ForeignKey(help_text='Entrepôt utilisé pour le déstockage', on_delete=django.db.models.deletion.PROTECT, related_name='politiques_restaurant', to='stock.entrepot')),
                ('etablissement', models.ForeignKey(blank=True, help_text='Établissement concerné (null = valeur par défaut)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politiques_stock', to='entreprises.etablissement')),
                ('point_vente', models.ForeignKey(blank=True, help_text="Point de vente concerné (null = valeur par défaut de l'établissement)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politiques_stock', to='pos.pointvente')),
            ],
            options={
                'verbose_name': 'Politique de stock restaurant',
                'verbose_name_plural': 'Politiques de stock restaurant',
                'db_table': 'stock_politique_stock_restaurant',
                'unique_together': {('etablissement', 'point_vente')},
            },
        ),
    ]
