# Generated by Django 6.0.5 on 2026-05-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_alter_comptefournisseur_fournisseur'),
        ('fournisseurs', '0001_initial'),
        ('stock', '0009_fournisseur_compte_comptable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fournisseurs.fournisseur'),
        ),
        migrations.AlterField(
            model_name='bonentree',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_entree', to='fournisseurs.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Fournisseur',
                ),
            ],
            database_operations=[],
        ),
    ]
