# Generated by Django 6.0.5 on 2026-06-03 13:49

import django.core.validators
from django.db import migrations, models
from decimal import Decimal


def copier_total(apps, schema_editor):
    BonEntree = apps.get_model('stock', 'BonEntree')
    LigneBonEntree = apps.get_model('stock', 'LigneBonEntree')
    for b in BonEntree.objects.all():
        b.total = b.total_ttc
        b.save()
    for l in LigneBonEntree.objects.all():
        l.montant = l.montant_ttc
        l.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_lot_fournisseur_alter_bonentree_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonentree',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='lignebonentree',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant'),
        ),
        migrations.RunPython(copier_total, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='bonentree',
            name='total_ht',
        ),
        migrations.RemoveField(
            model_name='bonentree',
            name='total_ttc',
        ),
        migrations.RemoveField(
            model_name='bonentree',
            name='total_tva',
        ),
        migrations.RemoveField(
            model_name='lignebonentree',
            name='montant_ht',
        ),
        migrations.RemoveField(
            model_name='lignebonentree',
            name='montant_ttc',
        ),
        migrations.RemoveField(
            model_name='lignebonentree',
            name='montant_tva',
        ),
        migrations.RemoveField(
            model_name='lignebonentree',
            name='tva',
        ),
        migrations.AlterField(
            model_name='lignebonentree',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'achat unitaire"),
        ),
    ]
