# Generated by Django 6.0.5 on 2026-06-03 23:44

from django.db import migrations, models


def migrer_est_vendable(apps, schema_editor):
    Produit = apps.get_model('stock', 'Produit')
    Produit.objects.filter(type_article='MARCHANDISE').update(est_vendable=True)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_bonentree_total_ht_remove_bonentree_total_ttc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_vendable',
            field=models.BooleanField(default=False, verbose_name='Visible dans le catalogue'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type_article',
            field=models.CharField(choices=[('MARCHANDISE', 'Marchandise'), ('MATIERE_PREMIERE', 'Matière première'), ('EMBALLAGE', 'Emballage'), ('CONSOMMABLE', 'Consommable interne'), ('IMMOBILISATION', 'Immobilisation'), ('SERVICE', 'Service')], default='MARCHANDISE', max_length=30),
        ),
        migrations.RunPython(migrer_est_vendable, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='produit',
            name='type_gestion',
        ),
    ]
