# Generated by Django 6.0.5 on 2026-06-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_remove_produit_type_gestion_produit_est_vendable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepot',
            name='type_entrepot',
            field=models.CharField(choices=[('CENTRAL', 'Magasin Central'), ('BAR', 'Bar'), ('BRASSERIE', 'Brasserie'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hôtel'), ('CUISINE', 'Cuisine'), ('SPA', 'Spa'), ('MINIBAR', 'Mini-bar')], max_length=20),
        ),
    ]
