# Generated by Django 5.2.13 on 2026-06-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_seed_brasserie_entrepot_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('INITIALISATION', 'Initialisation')], default='ENTREE', max_length=20),
        ),
    ]
