# Generated by Django 5.2.13 on 2026-06-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_alter_mouvementstock_type_mouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneinventaire',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Prix d'achat unitaire"),
        ),
    ]
