# Generated by Django 5.2.11 on 2026-07-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_stockentrepot_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='motif',
            field=models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente'), ('consommation', 'Consommation'), ('perte', 'Perte'), ('production', 'Production'), ('reapprovisionnement', 'Réapprovisionnement'), ('inventaire', 'Inventaire'), ('stock_initial', 'Stock initial')], default='achat', max_length=30),
        ),
    ]
