# Generated by Django 5.2.11 on 2026-07-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_alter_mouvementstock_motif'),
    ]

    operations = [
    ]
