# Generated by Django 5.2.13 on 2026-05-08 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tresorerie', '0002_mouvementcaisse_annule_mouvementcaisse_annule_le_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_paiement', models.CharField(choices=[('VENTE', 'Vente'), ('ACHAT', 'Achat fournisseur'), ('SALAIRE', 'Salaire'), ('AVANCE', 'Avance salaire'), ('REMBOURSEMENT', 'Remboursement'), ('TRANSFERT', 'Transfert'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sens', models.CharField(choices=[('ENTREE', 'Entrée (encaissement)'), ('SORTIE', 'Sortie (décaissement)')], default='SORTIE', max_length=20)),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='BROUILLON', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('est_comptabilise', models.BooleanField(default=False)),
                ('date_comptabilisation', models.DateTimeField(blank=True, null=True)),
                ('piece_comptable_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_externe', models.CharField(blank=True, max_length=100, null=True)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('taux_change', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='tresorerie.caisse')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiements',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['reference'], name='paiements_referen_e8a0ef_idx'), models.Index(fields=['content_type', 'object_id'], name='paiements_content_d6a8ad_idx'), models.Index(fields=['date'], name='paiements_date_b91f0c_idx'), models.Index(fields=['statut'], name='paiements_statut_ce5cce_idx'), models.Index(fields=['type_paiement'], name='paiements_type_pa_7e6931_idx')],
            },
        ),
    ]
