# Generated by Django 5.2.11 on 2026-07-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_paiement', models.CharField(choices=[('VENTE', 'Vente'), ('ACHAT', 'Achat fournisseur'), ('SALAIRE', 'Salaire'), ('AVANCE', 'Avance salaire'), ('DEPOT', 'Dépôt client'), ('REMBOURSEMENT', 'Remboursement'), ('TRANSFERT', 'Transfert'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sens', models.CharField(choices=[('ENTREE', 'Entrée (encaissement)'), ('SORTIE', 'Sortie (décaissement)')], default='SORTIE', max_length=20)),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('CREDIT', 'Crédit'), ('SOLDE', 'Solde client')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='BROUILLON', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('est_comptabilise', models.BooleanField(default=False)),
                ('date_comptabilisation', models.DateTimeField(blank=True, null=True)),
                ('piece_comptable_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_externe', models.CharField(blank=True, max_length=100, null=True)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('taux_change', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiements',
                'ordering': ['-date'],
            },
        ),
    ]
