# Generated by Django 5.2.13 on 2026-05-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='object_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
