# Generated by Django 5.2.11 on 2026-07-24 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('paiements', '0001_initial'),
        ('tresorerie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='tresorerie.caisse'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='clients.client'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['reference'], name='paiements_referen_e8a0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['content_type', 'object_id'], name='paiements_content_d6a8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date'], name='paiements_date_b91f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='paiements_statut_ce5cce_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['type_paiement'], name='paiements_type_pa_7e6931_idx'),
        ),
    ]
