# Generated by Django 6.0.5 on 2026-05-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_delete_clientmodel_and_more'),
        ('paiements', '0002_alter_paiement_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='clients.client'),
        ),
    ]
