# Generated by Django 6.0.5 on 2026-06-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('paiements', '0003_paiement_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('VENTE', 'Vente'), ('ACHAT', 'Achat fournisseur'), ('SALAIRE', 'Salaire'), ('AVANCE', 'Avance salaire'), ('DEPOT', 'Dépôt client'), ('REMBOURSEMENT', 'Remboursement'), ('TRANSFERT', 'Transfert'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
    ]
