# Generated by Django 5.0.14 on 2026-07-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_make_content_type_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('CREDIT', 'Crédit'), ('SOLDE', 'Solde client')], max_length=20),
        ),
    ]
