# Generated by Django 5.2.11 on 2026-07-24 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneeExploitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_metier', models.DateField(help_text="La date logique de cette journée d'exploitation", unique=True)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée'), ('CLOTUREE', 'Clôturée (Audit validé)')], default='OUVERTE', max_length=20)),
                ('fermee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journees_fermees', to='rh.employe')),
                ('ouverte_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journees_ouvertes', to='rh.employe')),
            ],
            options={
                'verbose_name': "Journée d'exploitation",
                'verbose_name_plural': "Journées d'exploitation",
                'db_table': 'core_journee_exploitation',
                'ordering': ['-date_metier'],
            },
        ),
    ]
