# Generated by Django 5.2.11 on 2026-07-26 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='Module source (ex: VENTE, STOCK, PAIEMENT)', max_length=50)),
                ('operation', models.CharField(help_text='Opération (ex: COMPTABILISATION, CONSOMMATION)', max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('RETRYING', 'Nouvelle tentative'), ('RESOLVED', 'Résolu'), ('IGNORED', 'Ignoré')], default='OPEN', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': "Erreur d'intégration",
                'verbose_name_plural': "Erreurs d'intégration",
                'db_table': 'core_integration_errors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_integr_status_ab4447_idx'), models.Index(fields=['module'], name='core_integr_module_422f39_idx'), models.Index(fields=['content_type', 'object_id'], name='core_integr_content_88dfc2_idx')],
            },
        ),
    ]
