# Generated by Django 5.2.11 on 2026-07-24 09:53

import apps.paie.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubriquePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_rubrique', models.CharField(choices=[('BASE', 'Salaire de base'), ('PRIME', 'Prime'), ('AVANTAGE', 'Avantage'), ('RETENUE', 'Retenue'), ('COTISATION', 'Cotisation'), ('IMPOT', 'Impôt')], max_length=20)),
                ('sens', models.CharField(choices=[('BRUT', 'Ajout (brut)'), ('NET', 'Déduction (net)')], default='BRUT', max_length=10)),
                ('taux', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.CharField(default=apps.paie.models.generate_id, max_length=50, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.CharField(max_length=200)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_approbation', models.DateField(blank=True, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('mois_remboursement', models.IntegerField(help_text='Mois de remboursement (1-12)')),
                ('annee_remboursement', models.IntegerField(help_text='Année de remboursement')),
                ('nombre_mois', models.IntegerField(default=1, help_text="Nombre de mois d'étalement")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('PAYEE', 'Payée'), ('REJETEE', 'Rejetée'), ('REMBOURSEE', 'Remboursée')], default='EN_ATTENTE', max_length=20)),
                ('approuve_par', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='rh.employe')),
            ],
            options={
                'db_table': 'paie_avances',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='PeriodePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cloture', models.BooleanField(default=False)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'unique_together': {('annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.CharField(default=apps.paie.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('base_calcul', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_brut', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cotisations', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_impots', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CALCULE', 'Calculé'), ('VALIDE', 'Validé'), ('EDITE', 'Édité')], default='BROUILLON', max_length=20)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.contrat')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='rh.employe')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='paie.periodepaie')),
            ],
            options={
                'ordering': ['-periode__annee', '-periode__mois'],
                'unique_together': {('employe', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='LigneBulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordre', models.IntegerField(default=0)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paie.bulletinpaie')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paie.rubriquepaie')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='LigneRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rembourse', models.BooleanField(default=False)),
                ('date_remboursement', models.DateField(blank=True, null=True)),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='paie.avancesalaire')),
                ('bulletin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='paie.bulletinpaie')),
            ],
            options={
                'db_table': 'paie_lignes_remboursement',
                'unique_together': {('avance', 'mois', 'annee')},
            },
        ),
    ]
