POINT_VENTE_GROUP_MAPPING = {
    'BAR': 'BAR',
    'RESTAURANT': 'RESTAURANT',
    'RECEPTION': 'CAISSIER',
    'ROOM_SERVICE': 'CAISSIER',
    'VIP': 'CAISSIER',
    'TERRASSE': 'CAISSIER',
    'GUICHET': 'RAF',
}
