# Generated by Django 5.2.13 on 2026-05-07 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PHYSIQUE', 'Caisse physique'), ('BANQUE', 'Compte bancaire')], default='PHYSIQUE', max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_comptable', models.ForeignKey(blank=True, help_text='Compte comptable associé (57xx pour caisse, 52xx pour banque)', limit_choices_to=models.Q(('code__startswith', '57'), ('code__startswith', '52'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptemodel')),
                ('point_vente', models.ForeignKey(blank=True, help_text='Point de vente associé à cette caisse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisses', to='pos.pointvente')),
            ],
            options={
                'db_table': 'tresorerie_caisses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_journal', models.DateField(auto_now_add=True)),
                ('solde_ouverture', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_entrees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sorties', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_reel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ecart', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cloture', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='tresorerie.caisse')),
            ],
            options={
                'verbose_name': 'Journal de caisse',
                'verbose_name_plural': 'Journaux de caisse',
                'db_table': 'tresorerie_journaux',
                'unique_together': {('caisse', 'date_journal')},
            },
        ),
        migrations.CreateModel(
            name='LigneJournalCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sens', models.CharField(max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle', models.CharField(max_length=255)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='tresorerie.journalcaisse')),
            ],
            options={
                'db_table': 'tresorerie_journal_lignes',
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('libelle', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='tresorerie.caisse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'db_table': 'tresorerie_mouvements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransfertCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='tresorerie.caisse')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='tresorerie.caisse')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfert',
                'verbose_name_plural': 'Transferts',
                'db_table': 'tresorerie_transferts',
            },
        ),
    ]
