# Generated by Django 5.2.13 on 2026-05-08 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tresorerie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcaisse',
            name='annule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annulations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='mouvement_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annulations_liees', to='tresorerie.mouvementcaisse'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
