# Generated by Django 6.0.5 on 2026-05-31 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0002_mouvementcaisse_annule_mouvementcaisse_annule_le_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='caisse_centrale',
            field=models.ForeignKey(blank=True, help_text='Caisse centrale où déposer les excédents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisses_secondaires', to='tresorerie.caisse'),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='type',
            field=models.CharField(choices=[('CENTRALE', 'Caisse centrale'), ('SECONDAIRE', 'Caisse secondaire'), ('BANQUE', 'Compte bancaire')], default='CENTRALE', max_length=20),
        ),
    ]
