# Generated by Django 5.2.13 on 2026-06-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0003_caisse_caisse_centrale_alter_caisse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='type',
            field=models.CharField(choices=[('CENTRALE', 'Caisse centrale'), ('POINT_VENTE', 'Caisse point de vente'), ('BANQUE', 'Compte bancaire')], default='CENTRALE', max_length=20),
        ),
    ]
