# Generated by Django 5.2.13 on 2026-06-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0004_alter_caisse_type'),
    ]

    operations = [
    ]
