# Generated by Django 5.2.13 on 2026-06-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0005_auto_20260609_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='type',
            field=models.CharField(choices=[('CENTRALE', 'Caisse centrale'), ('POINT_VENTE', 'Caisse point de vente')], default='CENTRALE', max_length=20),
        ),
    ]
