# Generated by Django 5.2.13 on 2026-06-11 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_parametreentreprise_compte_contrepartie_stock'),
        ('pos', '0015_setup_raf_employe'),
        ('tresorerie', '0007_migrate_banque_to_centrale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={'ordering': ['code'], 'verbose_name': 'Compte financier', 'verbose_name_plural': 'Comptes financiers'},
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='type',
        ),
        migrations.AddField(
            model_name='caisse',
            name='role',
            field=models.CharField(blank=True, choices=[('CENTRALE', 'Caisse centrale'), ('POINT_VENTE', 'Point de vente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='caisse',
            name='type_financier',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('BANQUE', 'Compte bancaire'), ('MOBILE_MONEY', 'Monnaie électronique')], default='ESPECES', max_length=20),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='compte_comptable',
            field=models.ForeignKey(blank=True, help_text='Compte comptable associé', limit_choices_to=models.Q(('code__startswith', '57'), ('code__startswith', '52'), ('code__startswith', '581'), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptemodel'),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='point_vente',
            field=models.ForeignKey(blank=True, help_text='Point de vente associé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisses', to='pos.pointvente'),
        ),
    ]
