# Generated by Django 5.2.13 on 2026-06-15 14:30

from django.db import migrations, models
from decimal import Decimal


def assigner_comptes_comptables(apps, schema_editor):
    """Attribue un compte comptable à chaque caisse qui n'en a pas"""
    Caisse = apps.get_model('tresorerie', 'Caisse')
    CompteModel = apps.get_model('comptabilite', 'CompteModel')

    def trouver_ou_creer(code, libelle, nature='ACTIF', sens='DEBIT', parent=None,
                         niveau=4, type_compte='sous_compte', categorie='bilan'):
        compte = CompteModel.objects.filter(code=code).first()
        if not compte:
            compte = CompteModel.objects.create(
                code=code, libelle=libelle, nature=nature, sens=sens,
                parent=parent, niveau=niveau, type_compte=type_compte,
                categorie=categorie, est_mouvement=True, actif=True,
            )
        return compte

    def get_parent_571():
        p57 = trouver_ou_creer('57', 'CAISSES', niveau=2, type_compte='groupe')
        return trouver_ou_creer('571', 'CAISSE SIEGE SOCIAL', parent=p57, niveau=3, type_compte='compte')

    parent_571 = get_parent_571()

    for c in Caisse.objects.all():
        if c.compte_comptable_id:
            continue

        if c.type_financier == 'ESPECES' and c.role == 'CENTRALE':
            compte = trouver_ou_creer('5711', c.nom, parent=parent_571)
        elif c.type_financier == 'ESPECES':
            derniers = CompteModel.objects.filter(
                code__startswith='571'
            ).exclude(code__in=['57', '571']).values_list('code', flat=True).order_by('code')
            max_num = 0
            for code in derniers:
                try:
                    n = int(code[3:])
                    if n > max_num:
                        max_num = n
                except (ValueError, TypeError):
                    pass
            next_code = f"571{max_num + 1}"
            compte = trouver_ou_creer(next_code, c.nom, parent=parent_571)
        elif c.type_financier == 'BANQUE':
            p52 = trouver_ou_creer('52', 'BANQUES', niveau=2, type_compte='groupe')
            compte = trouver_ou_creer('5211', c.nom, parent=p52, niveau=3, type_compte='compte')
        else:
            p581 = trouver_ou_creer('581', "REGIES D'AVANCE, ACCREDITIFS ET VIREMENTS INTERNES",
                                    niveau=3, type_compte='compte')
            compte = trouver_ou_creer('5811', c.nom, parent=p581)

        c.compte_comptable = compte
        c.save(update_fields=['compte_comptable'])


def nettoyer_doublons(apps, schema_editor):
    """Desactive les doublons et fusionne les soldes"""
    Caisse = apps.get_model('tresorerie', 'Caisse')
    MouvementCaisse = apps.get_model('tresorerie', 'MouvementCaisse')

    # 1. Doublon Orange Money (desactiver le second)
    om_list = list(Caisse.objects.filter(nom='Orange Money', type_financier='MOBILE_MONEY').order_by('id'))
    if len(om_list) > 1:
        garder = om_list[0]
        for dup in om_list[1:]:
            MouvementCaisse.objects.filter(caisse=dup).update(caisse=garder)
            dup.actif = False
            dup.save(update_fields=['actif'])

    # 2. Caisse Bar (ID 3) -> fusionner solde dans caisse Bar (ID 1) puis desactiver
    caisse_bar_big = Caisse.objects.filter(nom__iexact='caisse bar', type_financier='ESPECES').order_by('-solde').first()
    caisse_bar_small = Caisse.objects.filter(nom__iexact='caisse bar', type_financier='ESPECES').order_by('solde').first()
    if caisse_bar_big and caisse_bar_small and caisse_bar_big.id != caisse_bar_small.id:
        MouvementCaisse.objects.filter(caisse=caisse_bar_small).update(caisse=caisse_bar_big)
        caisse_bar_big.solde += caisse_bar_small.solde
        caisse_bar_big.save(update_fields=['solde'])
        caisse_bar_small.actif = False
        caisse_bar_small.save(update_fields=['actif'])


def renommer_caisses(apps, schema_editor):
    """Renomme les caisses selon la nomenclature standard"""
    Caisse = apps.get_model('tresorerie', 'Caisse')
    renoms = {
        'caisse Bar': 'Caisse Restaurant',
        'Caisse Bar 2': 'Caisse Brasserie',
    }
    for ancien, nouveau in renoms.items():
        Caisse.objects.filter(nom=ancien).update(nom=nouveau)


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0009_migrate_type_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='role',
            field=models.CharField(blank=True, choices=[('CENTRALE', 'Caisse centrale'), ('POINT_VENTE', 'Point de vente'), ('GUICHET', 'Guichet')], max_length=20, null=True),
        ),
        migrations.RunPython(assigner_comptes_comptables, migrations.RunPython.noop),
        migrations.RunPython(nettoyer_doublons, migrations.RunPython.noop),
        migrations.RunPython(renommer_caisses, migrations.RunPython.noop),
    ]
