# Generated by Django 5.2.13 on 2026-06-15 14:38

from django.db import migrations


def assigner_plages_correctes(apps, schema_editor):
    """Corrige les comptes comptables pour respecter les plages :
    - POINT_VENTE -> 5712-57149
    - GUICHET    -> 57150-57199
    - MOBILE_MONEY -> 5811-58199
    """
    Caisse = apps.get_model('tresorerie', 'Caisse')
    CompteModel = apps.get_model('comptabilite', 'CompteModel')

    def trouver_ou_creer(code, libelle, parent=None, niveau=4, type_compte='sous_compte'):
        c = CompteModel.objects.filter(code=code).first()
        if not c:
            c = CompteModel.objects.create(
                code=code, libelle=libelle,
                nature='ACTIF', sens='DEBIT',
                parent=parent, niveau=niveau,
                type_compte=type_compte,
                categorie='bilan',
                est_mouvement=True, actif=True,
            )
        return c

    def parent_571():
        p57 = CompteModel.objects.filter(code='57').first()
        if not p57:
            p57 = CompteModel.objects.create(
                code='57', libelle='CAISSES',
                nature='ACTIF', sens='DEBIT',
                parent=None, niveau=2,
                type_compte='groupe', categorie='bilan',
                est_mouvement=True, actif=True,
            )
        p571 = CompteModel.objects.filter(code='571').first()
        if not p571:
            p571 = CompteModel.objects.create(
                code='571', libelle='CAISSE SIEGE SOCIAL',
                nature='ACTIF', sens='DEBIT',
                parent=p57, niveau=3,
                type_compte='compte', categorie='bilan',
                est_mouvement=True, actif=True,
            )
        return p571

    def parent_581():
        p581 = CompteModel.objects.filter(code='581').first()
        if not p581:
            p581 = CompteModel.objects.create(
                code='581', libelle="REGIES D'AVANCE, ACCREDITIFS ET VIREMENTS INTERNES",
                nature='ACTIF', sens='DEBIT',
                parent=None, niveau=3,
                type_compte='compte', categorie='bilan',
                est_mouvement=True, actif=True,
            )
        return p581

    def max_num_in_range(prefix, debut, fin):
        max_trouve = debut - 1
        for c in CompteModel.objects.filter(code__startswith=prefix).exclude(
            code__in=['57', '571', '5711']
        ).values_list('code', flat=True):
            try:
                n = int(c[len(prefix):])
                if debut <= n <= fin:
                    max_trouve = max(max_trouve, n)
            except (ValueError, IndexError):
                pass
        return max_trouve

    p571 = parent_571()
    p581 = parent_581()

    # 1. ID 2 "CAISSE GUICHE 2" -> POINT_VENTE -> prochain dans 5712-57149
    guiche2 = Caisse.objects.filter(id=2).first()
    if guiche2 and guiche2.compte_comptable_id:
        old = guiche2.compte_comptable
        max_n = max_num_in_range('571', 2, 49)
        next_code = f"571{max_n + 1}"
        compte = trouver_ou_creer(next_code, guiche2.nom, parent=p571)
        guiche2.compte_comptable = compte
        guiche2.save(update_fields=['compte_comptable'])
        # Si l'ancien code 571 était un parent et n'est plus utilisé, on le garde

    # 2. ID 6 "Caisse Centrale RAF" -> GUICHET -> role=GUICHET, code 57150-57199
    raf = Caisse.objects.filter(id=6).first()
    if raf:
        raf.role = 'GUICHET'
        max_n = max_num_in_range('571', 50, 99)
        next_code = f"571{max_n + 1}"
        compte = trouver_ou_creer(next_code, raf.nom, parent=p571)
        raf.compte_comptable = compte
        raf.save(update_fields=['role', 'compte_comptable'])

    # 3. ID 7 "Orange Money" (active) -> MOBILE_MONEY -> prochain dans 5811-58199
    om = Caisse.objects.filter(id=7).first()
    if om and om.compte_comptable and om.compte_comptable.code == '581':
        max_n = max_num_in_range('581', 1, 99)
        next_code = f"581{max_n + 1}"
        compte = trouver_ou_creer(next_code, om.nom, parent=p581)
        om.compte_comptable = compte
        om.save(update_fields=['compte_comptable'])


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0010_ajout_guichet_et_nettoyage'),
    ]

    operations = [
        migrations.RunPython(assigner_plages_correctes, migrations.RunPython.noop),
    ]
