# Generated by Django 5.2.11 on 2026-07-24 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rh_departements',
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('intitule', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('Ouvrier', 'Ouvrier'), ('Employe', 'Employé'), ('Technicien', 'Technicien'), ('AgentMaitrise', 'Agent de maîtrise'), ('Cadre', 'Cadre')], max_length=20)),
                ('coefficient', models.IntegerField(blank=True, null=True)),
                ('niveau', models.CharField(blank=True, max_length=10, null=True)),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'rh_postes',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('situation_familiale', models.CharField(choices=[('Celibataire', 'Célibataire'), ('Marie', 'Marié(e)'), ('Pacse', 'Pacsé(e)'), ('Divorce', 'Divorcé(e)'), ('Veuf', 'Veuf/Veuve')], default='Celibataire', max_length=20)),
                ('nombre_enfants', models.IntegerField(default=0)),
                ('conjoint_civilite', models.CharField(blank=True, choices=[('M.', 'M.'), ('Mme', 'Mme')], default='', max_length=5, verbose_name='Civilité du conjoint')),
                ('conjoint_nom', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du conjoint')),
                ('conjoint_prenom', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom du conjoint')),
                ('conjoint_contact', models.CharField(blank=True, default='', max_length=20, verbose_name='Contact du conjoint')),
                ('personne_reference_nom', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom de la personne de référence')),
                ('personne_reference_prenom', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom de la personne de référence')),
                ('personne_reference_contact', models.CharField(blank=True, default='', max_length=20, verbose_name='Contact de la personne de référence')),
                ('salaire_fixe', models.DecimalField(decimal_places=2, default=0, help_text='Salaire mensuel fixe', max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/', verbose_name='Photo')),
                ('diplome', models.CharField(blank=True, default='', max_length=200, verbose_name="Diplôme / Niveau d'études")),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('actif', models.BooleanField(default=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='rh.departement')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe', to=settings.AUTH_USER_MODEL)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='rh.poste')),
            ],
            options={
                'db_table': 'rh_employes',
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to='rh.employe'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contrat', models.CharField(max_length=20, unique=True)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Interim', 'Intérim')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree_heures_mois', models.DecimalField(decimal_places=2, default=151.67, max_digits=6)),
                ('salaire_brut_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_cadre', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='rh.employe')),
            ],
            options={
                'db_table': 'rh_contrats',
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conge', models.CharField(max_length=20, unique=True)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_jours_ouvrables', models.IntegerField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Refusé', 'Refusé'), ('Annulé', 'Annulé')], default='En attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='rh.employe')),
            ],
            options={
                'db_table': 'rh_conges',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_absence', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_absence', models.CharField(choices=[('Maladie', 'Maladie'), ('Accident travail', 'Accident de travail'), ('Maternite', 'Maternité'), ('Sans solde', 'Sans solde'), ('Formation', 'Formation')], max_length=20)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('validee', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='rh.employe')),
            ],
            options={
                'db_table': 'rh_absences',
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pointage', models.CharField(max_length=20, unique=True)),
                ('date_pointage', models.DateField()),
                ('heure_entree', models.TimeField(blank=True, null=True)),
                ('heure_sortie', models.TimeField(blank=True, null=True)),
                ('pause_dejeuner', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('est_justifie', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='rh.employe')),
            ],
            options={
                'db_table': 'rh_pointages',
            },
        ),
    ]
