# Generated by Django 5.2.13 on 2026-05-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
