# Generated by Django 5.2.13 on 2026-05-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_ajout_statut_en_cours_de_livraison'),
        ('rh', '0002_alter_employe_adresse_alter_employe_date_embauche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='point_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='pos.pointvente'),
        ),
    ]
