# Generated by Django 6.0.5 on 2026-05-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_employe_point_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
