# Generated by Django 6.0.5 on 2026-06-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_alter_employe_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='conjoint_contact',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contact du conjoint'),
        ),
        migrations.AddField(
            model_name='employe',
            name='conjoint_nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du conjoint'),
        ),
        migrations.AddField(
            model_name='employe',
            name='conjoint_prenom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom du conjoint'),
        ),
        migrations.AddField(
            model_name='employe',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='employe',
            name='diplome',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Diplôme / Niveau d'études"),
        ),
        migrations.AddField(
            model_name='employe',
            name='personne_reference_contact',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contact de la personne de référence'),
        ),
        migrations.AddField(
            model_name='employe',
            name='personne_reference_nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom de la personne de référence'),
        ),
        migrations.AddField(
            model_name='employe',
            name='personne_reference_prenom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom de la personne de référence'),
        ),
    ]
