# Generated by Django 5.2.13 on 2026-06-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_employe_conjoint_contact_employe_conjoint_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='conjoint_civilite',
            field=models.CharField(blank=True, choices=[('M.', 'M.'), ('Mme', 'Mme')], default='', max_length=5, verbose_name='Civilité du conjoint'),
        ),
    ]
