# Generated by Django 5.2.13 on 2026-06-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_employe_conjoint_civilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employes/', verbose_name='Photo'),
        ),
    ]
