# Generated by Django 5.0.14 on 2026-07-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_employe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='salaire_fixe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salaire mensuel fixe', max_digits=10),
        ),
    ]
