# Generated by Django 5.2.11 on 2026-07-23 23:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComportementArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockable', models.BooleanField(default=True, verbose_name='Stockable')),
                ('vendable', models.BooleanField(default=True, verbose_name='Vendable')),
                ('achetable', models.BooleanField(default=True, verbose_name='Achetable')),
                ('perissable', models.BooleanField(default=False, verbose_name='PÃ©rissable')),
                ('lot_obligatoire', models.BooleanField(default=False, verbose_name='Lot obligatoire')),
                ('numero_serie', models.BooleanField(default=False, verbose_name='NumÃ©ro de sÃ©rie')),
                ('inventoriable', models.BooleanField(default=True, verbose_name='Inventoriable')),
            ],
            options={
                'verbose_name': "Comportement d'article",
                'verbose_name_plural': "Comportements d'article",
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, verbose_name='LibellÃ©')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CrÃ©Ã© le')),
            ],
            options={
                'verbose_name': 'DÃ©pÃ´t',
                'verbose_name_plural': 'DÃ©pÃ´ts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TypeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, verbose_name='LibellÃ©')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Type d'article",
                'verbose_name_plural': "Types d'article",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='LibellÃ©')),
                ('categorie', models.CharField(choices=[('MASSE', 'Masse'), ('VOLUME', 'Volume'), ('UNITE', 'UnitÃ©'), ('LONGUEUR', 'Longueur'), ('SURFACE', 'Surface'), ('TEMPS', 'Temps'), ('MONNAIE', 'Monnaie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name="CatÃ©gorie d'unitÃ©")),
            ],
            options={
                'verbose_name': 'UnitÃ©',
                'verbose_name_plural': 'UnitÃ©s',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='stocks.categoriearticle', verbose_name='CatÃ©gorie parente')),
            ],
            options={
                'verbose_name': "CatÃ©gorie d'article",
                'verbose_name_plural': "CatÃ©gories d'article",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code article')),
                ('designation', models.CharField(max_length=500, verbose_name='DÃ©signation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('methode_valorisation', models.CharField(choices=[('PMP', 'Prix Moyen PondÃ©rÃ©'), ('FIFO', 'Premier entrÃ©, premier sorti'), ('DMP', "Dernier prix d'achat"), ('NONE', 'Aucune')], default='PMP', max_length=10, verbose_name='MÃ©thode de valorisation')),
                ('seuil_alerte', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name="Seuil d'alerte")),
                ('stock_min', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Stock minimum')),
                ('stock_max', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Stock maximum')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CrÃ©Ã© le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis Ã\xa0 jour le')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='stocks.categoriearticle', verbose_name='CatÃ©gorie')),
                ('comportement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='stocks.comportementarticle', verbose_name='Comportement')),
                ('type_article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='stocks.typearticle', verbose_name="Type d'article")),
                ('unite_defaut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='stocks.unite', verbose_name='UnitÃ© par dÃ©faut')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, verbose_name='LibellÃ©')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='stocks.depot', verbose_name='DÃ©pÃ´t')),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
                'ordering': ['depot', 'code'],
                'unique_together': {('depot', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='RÃ©fÃ©rence')),
                ('date_inventaire', models.DateField(verbose_name="Date d'inventaire")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('VALIDE', 'ValidÃ©'), ('ANNULE', 'AnnulÃ©')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('realise_par', models.CharField(blank=True, max_length=255, verbose_name='RÃ©alisÃ© par')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CrÃ©Ã© le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis Ã\xa0 jour le')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='stocks.depot', verbose_name='DÃ©pÃ´t')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=100, unique=True, verbose_name='NÂ° de lot')),
                ('date_fabrication', models.DateField(blank=True, null=True, verbose_name='Date de fabrication')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de pÃ©remption')),
                ('prix_revient_unitaire', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Prix de revient unitaire')),
                ('quantite_initiale', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='QuantitÃ© initiale')),
                ('quantite_restante', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='QuantitÃ© restante')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CrÃ©Ã© le')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='stocks.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='QuantitÃ© thÃ©orique')),
                ('quantite_reelle', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='QuantitÃ© rÃ©elle')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='stocks.article', verbose_name='Article')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stocks.inventaire', verbose_name='Inventaire')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_inventaire', to='stocks.lot', verbose_name='Lot')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='RÃ©fÃ©rence')),
                ('nature', models.CharField(choices=[('ENTREE', 'EntrÃ©e'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT', 'Ajustement')], max_length=20, verbose_name='Nature du mouvement')),
                ('reference_externe', models.CharField(blank=True, help_text='RÃ©fÃ©rence libre du document mÃ©tier (ex: FAC-2026-001254)', max_length=255, verbose_name='RÃ©f. externe')),
                ('quantite', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='QuantitÃ©')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Prix unitaire')),
                ('cout_total', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='CoÃ»t total')),
                ('date_mouvement', models.DateTimeField(verbose_name='Date du mouvement')),
                ('libelle', models.CharField(blank=True, max_length=500, verbose_name='LibellÃ©')),
                ('valide', models.BooleanField(default=False, verbose_name='ValidÃ©')),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID source')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='CrÃ©Ã© par')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CrÃ©Ã© le')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.article', verbose_name='Article')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.depot', verbose_name='DÃ©pÃ´t')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='stocks.emplacement', verbose_name='Emplacement')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='stocks.lot', verbose_name='Lot')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Type de source')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='JournalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('nature', models.CharField(max_length=20, verbose_name='Nature du mouvement')),
                ('quantite', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='QuantitÃ©')),
                ('stock_avant', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Stock avant')),
                ('stock_apres', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Stock aprÃ¨s')),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='CoÃ»t unitaire')),
                ('libelle', models.CharField(blank=True, max_length=500, verbose_name='LibellÃ©')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='CrÃ©Ã© par')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CrÃ©Ã© le')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_journal', to='stocks.article', verbose_name='Article')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_journal', to='stocks.depot', verbose_name='DÃ©pÃ´t')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_journal', to='stocks.mouvementstock', verbose_name='Mouvement')),
            ],
            options={
                'verbose_name': 'Ã‰criture du journal de stock',
                'verbose_name_plural': 'Journal de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CoucheValorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_restante', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='QuantitÃ© restante')),
                ('prix_unitaire', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Prix unitaire')),
                ('date_entree', models.DateTimeField(verbose_name="Date d'entrÃ©e")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couches_valorisation', to='stocks.article', verbose_name='Article')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couches_valorisation', to='stocks.depot', verbose_name='DÃ©pÃ´t')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couches_valorisation', to='stocks.lot', verbose_name='Lot')),
                ('mouvement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couches_valorisation', to='stocks.mouvementstock', verbose_name="Mouvement d'origine")),
            ],
            options={
                'verbose_name': 'Couche de valorisation',
                'verbose_name_plural': 'Couches de valorisation',
                'ordering': ['date_entree', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code nomenclature')),
                ('libelle', models.CharField(max_length=500, verbose_name='LibellÃ©')),
                ('quantite_produite', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='QuantitÃ© produite')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CrÃ©Ã© le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis Ã\xa0 jour le')),
                ('article_compose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures_compose', to='stocks.article', verbose_name='Article composÃ©')),
            ],
            options={
                'verbose_name': 'Nomenclature',
                'verbose_name_plural': 'Nomenclatures',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ComposantNomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='QuantitÃ©')),
                ('perte', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de perte (%)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomenclatures_composant', to='stocks.article', verbose_name='Article composant')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='stocks.nomenclature', verbose_name='Nomenclature')),
            ],
            options={
                'verbose_name': 'Composant de nomenclature',
                'verbose_name_plural': 'Composants de nomenclature',
                'ordering': ['nomenclature', 'article'],
            },
        ),
        migrations.CreateModel(
            name='NumeroSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='NÂ° de sÃ©rie')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CrÃ©Ã© le')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_serie', to='stocks.article', verbose_name='Article')),
                ('depot_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeros_serie', to='stocks.depot', verbose_name='DÃ©pÃ´t actuel')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeros_serie', to='stocks.lot', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'NumÃ©ro de sÃ©rie',
                'verbose_name_plural': 'NumÃ©ros de sÃ©rie',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SourceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('famille', models.CharField(choices=[('APPROVISIONNEMENT', 'Approvisionnement'), ('DISTRIBUTION', 'Distribution'), ('PRODUCTION', 'Production'), ('LOGISTIQUE', 'Logistique'), ('INCIDENTS', 'Incidents'), ('TECHNIQUE', 'Technique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30, verbose_name='Famille')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('systeme', models.BooleanField(default=False, verbose_name='SystÃ¨me')),
            ],
            options={
                'verbose_name': 'OpÃ©ration source',
                'verbose_name_plural': 'OpÃ©rations source',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['famille'], name='stocks_sour_famille_40c795_idx')],
            },
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='source_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.sourceoperation', verbose_name='OpÃ©ration source'),
        ),
        migrations.CreateModel(
            name='ConditionnementArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du conditionnement')),
                ('facteur_conversion', models.DecimalField(decimal_places=6, help_text="Nombre d'unités de base dans ce conditionnement", max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Facteur de conversion')),
                ('achat', models.BooleanField(default=True, verbose_name="Conditionnement d'achat")),
                ('vente', models.BooleanField(default=False, verbose_name='Conditionnement de vente')),
                ('stock', models.BooleanField(default=False, verbose_name='Conditionnement de stock')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionnements', to='stocks.article', verbose_name='Article')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': "Conditionnement d'article",
                'verbose_name_plural': "Conditionnements d'article",
                'ordering': ['article', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Valorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('PMP', 'Prix Moyen PondÃ©rÃ©'), ('FIFO', 'Premier entrÃ©, premier sorti'), ('STANDARD', 'CoÃ»t standard'), ('NONE', 'Aucune')], default='PMP', max_length=10, verbose_name='MÃ©thode')),
                ('cout_unitaire_moyen', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='CoÃ»t unitaire moyen')),
                ('quantite_totale', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='QuantitÃ© totale')),
                ('valeur_totale', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Valeur totale')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re mise Ã\xa0 jour')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valorisations', to='stocks.article', verbose_name='Article')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valorisations', to='stocks.depot', verbose_name='DÃ©pÃ´t')),
            ],
            options={
                'verbose_name': 'Valorisation',
                'verbose_name_plural': 'Valorisations',
            },
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['article', 'date_peremption'], name='stocks_lot_article_91e90a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ligneinventaire',
            unique_together={('inventaire', 'article', 'lot')},
        ),
        migrations.AddIndex(
            model_name='journalstock',
            index=models.Index(fields=['article', 'depot'], name='stocks_jour_article_a739a6_idx'),
        ),
        migrations.AddIndex(
            model_name='journalstock',
            index=models.Index(fields=['date'], name='stocks_jour_date_389f77_idx'),
        ),
        migrations.AddIndex(
            model_name='couchevalorisation',
            index=models.Index(fields=['article', 'depot', 'date_entree'], name='stocks_couc_article_fde960_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['article', 'depot'], name='stocks_mouv_article_98f1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['nature'], name='stocks_mouv_nature_4320e1_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['date_mouvement'], name='stocks_mouv_date_mo_1b200f_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['valide'], name='stocks_mouv_valide_82a165_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='stocks_mouv_source__6b27b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conditionnementarticle',
            unique_together={('article', 'nom')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['code'], name='stocks_arti_code_870c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['type_article'], name='stocks_arti_type_ar_b1abac_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['actif'], name='stocks_arti_actif_96ecfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valorisation',
            unique_together={('article', 'depot')},
        ),
    ]
