// theme/static_src/tailwind.config.js
module.exports = {
  darkMode: "class",
  content: [
    "../../templates/**/*.html",
    "../../apps/**/templates/**/*.html",
    "../../apps/**/views.py",
  ],
  theme: {
    extend: {
      colors: {
        // Thème clair chaleureux (hôtel) — miroir de templates/partials/theme_head.html
        "surface-dim": "#f0ece3",
        "surface": "#faf8f4",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ffffff",
        "surface-container": "#f6f2ea",
        "surface-container-high": "#f0ece3",
        "surface-container-highest": "#e9e3d8",
        "surface-variant": "#e9e3d8",
        "on-surface": "#1f2937",
        "on-surface-variant": "#6b7280",
        "primary": "#c8962c",
        "primary-container": "#f7ecd3",
        "on-primary": "#ffffff",
        "on-primary-container": "#5a430f",
        "primary-fixed": "#f7ecd3",
        "primary-fixed-dim": "#e3c282",
        "on-primary-fixed": "#402d00",
        "on-primary-fixed-variant": "#5a430f",
        "secondary": "#c8962c",
        "secondary-container": "#f7ecd3",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5a430f",
        "secondary-fixed": "#f7ecd3",
        "secondary-fixed-dim": "#e3c282",
        "on-secondary-fixed": "#402d00",
        "on-secondary-fixed-variant": "#5a430f",
        "tertiary": "#6b7280",
        "tertiary-container": "#eef0f2",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#374151",
        "tertiary-fixed": "#eef0f2",
        "tertiary-fixed-dim": "#d1d5db",
        "on-tertiary-fixed": "#1f2937",
        "on-tertiary-fixed-variant": "#4b5563",
        "error": "#dc2626",
        "error-container": "#fee2e2",
        "on-error": "#ffffff",
        "on-error-container": "#7f1d1d",
        "outline": "#d6d3cd",
        "outline-variant": "#ece7dd",
        "inverse-surface": "#1f2937",
        "inverse-on-surface": "#faf8f4",
        "inverse-primary": "#e3c282",
        "surface-tint": "#c8962c",
        "background": "#faf8f4",
        "on-background": "#1f2937",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "section-gap": "120px",
        "margin-desktop": "80px",
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "24px",
      },
      fontFamily: {
        "headline-sm": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "ui-element": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "ui-element": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.2em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}

