// theme/static_src/tailwind.config.js
module.exports = {
  darkMode: "class",
  content: [
    "../../templates/**/*.html",
    "../../apps/**/templates/**/*.html",
    "../../apps/**/views.py",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131313",
        "surface": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#20201f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "surface-variant": "#353535",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c4c7c7",
        "primary": "#c9c6c5",
        "primary-container": "#050505",
        "on-primary": "#313030",
        "on-primary-container": "#797777",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c9c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        "secondary": "#e3c282",
        "secondary-container": "#5c4611",
        "on-secondary": "#402d00",
        "on-secondary-container": "#d4b475",
        "secondary-fixed": "#ffdea0",
        "secondary-fixed-dim": "#e3c282",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#5a430f",
        "tertiary": "#c7c6c6",
        "tertiary-container": "#040505",
        "on-tertiary": "#303031",
        "on-tertiary-container": "#777777",
        "tertiary-fixed": "#e4e2e2",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-tertiary-fixed": "#1b1c1c",
        "on-tertiary-fixed-variant": "#464747",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#8e9192",
        "outline-variant": "#444748",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#5f5e5e",
        "surface-tint": "#c9c6c5",
        "background": "#131313",
        "on-background": "#e5e2e1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "section-gap": "120px",
        "margin-desktop": "80px",
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "24px",
      },
      fontFamily: {
        "headline-sm": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "ui-element": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "ui-element": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.2em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}

