# Generated by Django 5.2.13 on 2026-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id_client', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('type_client', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('ENTREPRISE', 'Entreprise'), ('AGENCE', 'Agence de voyage')], default='PARTICULIER', max_length=20)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('BLACKLIST', 'Blacklisté')], default='ACTIF', max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['nom'],
            },
        ),
    ]
