# Generated by Django 5.2.11 on 2026-07-24 09:53

import apps.clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=apps.clients.models.generate_client_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('type_client', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('ENTREPRISE', 'Entreprise'), ('AGENCE', 'Agence de voyage')], default='PARTICULIER', max_length=20)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('BLACKLIST', 'Blacklisté')], default='ACTIF', max_length=20)),
                ('piece_identite', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_piece', models.CharField(blank=True, max_length=50, null=True)),
                ('identifiant_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('credit_plafond', models.DecimalField(decimal_places=2, default=0, help_text='Plafond de crédit (0 = pas de limite)', max_digits=12)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients_client',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom'], name='clients_cli_nom_0cf00c_idx'), models.Index(fields=['telephone'], name='clients_cli_telepho_8c69d9_idx'), models.Index(fields=['statut'], name='clients_cli_statut_d69dca_idx')],
            },
        ),
    ]
