# Generated by Django 5.0.14 on 2026-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rendre_telephone_obligatoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_plafond',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Plafond de crédit (0 = pas de limite)', max_digits=12),
        ),
    ]
