# Generated by Django 5.2.11 on 2026-07-23 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nom_commercial', models.CharField(blank=True, max_length=200)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('forme_juridique', models.CharField(blank=True, choices=[('EI', 'Entreprise individuelle'), ('SARL', 'SARL'), ('SA', 'SA'), ('SAS', 'SAS'), ('ASSOCIATION', 'Association'), ('AUTRE', 'Autre')], max_length=20)),
                ('nif', models.CharField(blank=True, max_length=100)),
                ('rccm', models.CharField(blank=True, max_length=100)),
                ('numero_statistique', models.CharField(blank=True, max_length=100)),
                ('numero_art', models.CharField(blank=True, max_length=100, verbose_name="Numéro d'agrément ART")),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Mali', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/')),
                ('cachet', models.ImageField(blank=True, null=True, upload_to='entreprises/cachets/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='entreprises/signatures/')),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('symbole_devise', models.CharField(default='FCFA', max_length=10)),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('fuseau_horaire', models.CharField(default='Africa/Bamako', max_length=100)),
                ('format_date', models.CharField(default='d/m/Y', max_length=30)),
                ('exercice_comptable_debut_mois', models.PositiveSmallIntegerField(default=1)),
                ('couleur_principale', models.CharField(default='#1F2937', max_length=20)),
                ('couleur_secondaire', models.CharField(default='#D4AF37', max_length=20)),
                ('pied_facture', models.TextField(blank=True)),
                ('conditions_facture', models.TextField(blank=True)),
                ('configuration_terminee', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='entreprises.entreprise')),
            ],
            options={
                'verbose_name': "Configuration de l'entreprise",
                'verbose_name_plural': "Configurations de l'entreprise",
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('type_etablissement', models.CharField(choices=[('HOTEL', 'Hôtel'), ('HOTEL_RESTAURANT', 'Hôtel-restaurant'), ('RESIDENCE', 'Résidence'), ('AUBERGE', 'Auberge'), ('COMPLEXE', 'Complexe hôtelier'), ('MOTEL', 'Motel'), ('AUTRE', 'Autre')], default='HOTEL', max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('nombre_etoiles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etablissements', to='entreprises.entreprise')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationHoteliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_check_in', models.TimeField(default='14:00')),
                ('heure_check_out', models.TimeField(default='12:00')),
                ('autoriser_arrivee_anticipee', models.BooleanField(default=True)),
                ('autoriser_depart_tardif', models.BooleanField(default=True)),
                ('pourcentage_acompte_reservation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('delai_annulation_gratuite_heures', models.PositiveIntegerField(default=24)),
                ('liberation_automatique_chambre', models.BooleanField(default=False)),
                ('passage_nettoyage_apres_depart', models.BooleanField(default=True)),
                ('autoriser_surclassement', models.BooleanField(default=True)),
                ('autoriser_changement_chambre', models.BooleanField(default=True)),
                ('texte_confirmation_reservation', models.TextField(blank=True)),
                ('politique_annulation', models.TextField(blank=True)),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_hoteliere', to='entreprises.etablissement')),
            ],
            options={
                'verbose_name': 'Configuration hôtelière',
                'verbose_name_plural': 'Configurations hôtelières',
            },
        ),
        migrations.CreateModel(
            name='ModuleEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('HOTEL', 'Hôtel'), ('RESTAURANT', 'Restaurant'), ('POS', 'Points de vente'), ('STOCK', 'Stocks'), ('FOURNISSEURS', 'Fournisseurs'), ('FACTURATION', 'Facturation'), ('PAIEMENTS', 'Paiements'), ('TRESORERIE', 'Trésorerie'), ('COMPTABILITE', 'Comptabilité'), ('RH', 'Ressources humaines'), ('PAIE', 'Paie')], max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='entreprises.entreprise')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'code'), name='unique_module_par_entreprise')],
            },
        ),
        migrations.CreateModel(
            name='SequenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('RESERVATION', 'Réservation'), ('SEJOUR', 'Séjour'), ('FACTURE', 'Facture'), ('RECU', 'Reçu'), ('AVOIR', 'Avoir'), ('COMMANDE', 'Commande'), ('ACHAT', 'Achat'), ('INVENTAIRE', 'Inventaire'), ('BON_LIVRAISON', 'Bon de livraison'), ('DEPENSE', 'Dépense'), ('TRANSFERT', 'Transfert')], max_length=30)),
                ('prefixe', models.CharField(max_length=20)),
                ('prochain_numero', models.PositiveBigIntegerField(default=1)),
                ('longueur_numero', models.PositiveSmallIntegerField(default=6)),
                ('reinitialisation_annuelle', models.BooleanField(default=True)),
                ('annee', models.PositiveSmallIntegerField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences_documents', to='entreprises.entreprise')),
            ],
            options={
                'verbose_name': 'Séquence de document',
                'verbose_name_plural': 'Séquences de documents',
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'type_document', 'annee'), name='unique_sequence_document_annee')],
            },
        ),
    ]
