# Generated by Django 5.2.13 on 2026-05-07 14:57

import apps.pos.models.vente
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
                'db_table': 'pos_lignes_vente',
            },
        ),
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('emplacement', models.CharField(choices=[('RESTAURANT', 'Restaurant principal'), ('BAR', 'Bar piscine'), ('VIP', 'VIP Lounge'), ('TERRASSE', 'Terrasse'), ('RECEPTION', 'Réception hôtel'), ('ROOM_SERVICE', 'Room service')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('imprimante_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('impression_auto', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
                'db_table': 'pos_points_vente',
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('solde_initial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_attendu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_fermee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'db_table': 'pos_sessions_caisse',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.CharField(default=apps.pos.models.vente.generate_vente_id, max_length=20, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('client_nom', models.CharField(blank=True, max_length=200, null=True)),
                ('chambre_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('COMPTE_CLIENT', 'Compte client (hôtel)'), ('FACTURE', 'Facture globale')], default='ESPECES', max_length=20)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'pos_ventes',
                'ordering': ['-created_at'],
            },
        ),
    ]
