# Generated by Django 5.2.11 on 2026-07-24 09:53

import apps.pos.models.commande
import apps.pos.models.vente
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaissePointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principale', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caisse de point de vente',
                'verbose_name_plural': 'Caisses de points de vente',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=apps.pos.models.commande.generate_commande_numero, max_length=20, unique=True)),
                ('type_commande', models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('EMPORTER', 'À emporter'), ('LIVRAISON', 'Livraison')], default='SUR_PLACE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_COURS_DE_LIVRAISON', 'En cours de livraison'), ('SERVIE', 'Servie'), ('LIVREE', 'Livrée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30)),
                ('client_nom', models.CharField(blank=True, max_length=200)),
                ('client_telephone', models.CharField(blank=True, max_length=20)),
                ('adresse_livraison', models.TextField(blank=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_preparation', models.DateTimeField(blank=True, null=True)),
                ('date_service', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'pos_commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComptageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especes_attendues', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('especes_comptees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ecart_especes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carte_attendue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carte_constatee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_attendu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_constate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cheque_attendu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cheque_constate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motif_ecart', models.TextField(blank=True)),
                ('compte_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comptage de session',
                'verbose_name_plural': 'Comptages de session',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'pos_lignes_commande',
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
                'db_table': 'pos_lignes_vente',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_livreur', models.CharField(blank=True, help_text='Nom libre si livreur non sélectionné', max_length=200)),
                ('adresse', models.TextField()),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'db_table': 'pos_livraisons',
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'db_table': 'pos_livreurs',
            },
        ),
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('type_pv', models.CharField(choices=[('RESTAURATION', 'Restauration'), ('BAR', 'Bar'), ('BOUTIQUE', 'Boutique'), ('RECEPTION', 'Réception'), ('ROOM_SERVICE', 'Room service'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30, verbose_name='Type')),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('imprimante_nom', models.CharField(blank=True, max_length=100)),
                ('impression_auto', models.BooleanField(default=True)),
                ('exiger_planning_pour_acces', models.BooleanField(default=True)),
                ('exiger_planning_pour_caisse', models.BooleanField(default=True)),
                ('mode_prelevement_stock', models.CharField(choices=[('STRICT', 'Entrepôt unique'), ('CASCADE', 'Entrepôts par priorité')], default='STRICT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
                'db_table': 'pos_points_vente',
            },
        ),
        migrations.CreateModel(
            name='PointVenteEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorite', models.PositiveSmallIntegerField(default=1)),
                ('principal', models.BooleanField(default=False)),
                ('autorise_vente', models.BooleanField(default=True)),
                ('autorise_retour', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Liaison point de vente ↔ entrepôt',
                'verbose_name_plural': 'Liaisons points de vente ↔ entrepôts',
                'db_table': 'pos_point_vente_entrepots',
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_attendu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('depot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fonds_collectes', models.BooleanField(default=False)),
                ('date_collecte', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COMPTAGE', 'En comptage'), ('FERMEE', 'Fermée'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'db_table': 'pos_sessions_caisse',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='ShiftEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_prevu', models.DateTimeField()),
                ('fin_prevue', models.DateTimeField()),
                ('debut_reel', models.DateTimeField(blank=True, null=True)),
                ('fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('CONFIRME', 'Confirmé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé'), ('ABSENT', 'Absent')], default='PLANIFIE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shift employé',
                'verbose_name_plural': 'Shifts employés',
                'ordering': ['-debut_prevu'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.CharField(default=apps.pos.models.vente.generate_vente_id, max_length=20, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('client_nom', models.CharField(blank=True, max_length=200, null=True)),
                ('chambre_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque'), ('CREDIT', 'Crédit'), ('SOLDE', 'Solde client'), ('COMPTE_CLIENT', 'Compte client'), ('FACTURE', 'Facture')], default='ESPECES', max_length=20)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'pos_ventes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifierLoopLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(default='session_verifier', max_length=50, unique=True)),
                ('detenteur', models.CharField(blank=True, help_text='hostname:pid du worker qui detient le verrou', max_length=200)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Verrou boucle de verification',
                'verbose_name_plural': 'Verrous boucle de verification',
                'db_table': 'pos_verifier_loop_lock',
            },
        ),
        migrations.CreateModel(
            name='AffectationPointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CAISSIER', 'Caissier'), ('SERVEUR', 'Serveur'), ('RESPONSABLE', 'Responsable'), ('SUPERVISEUR', 'Superviseur'), ('PREPARATEUR', 'Préparateur')], default='CAISSIER', max_length=30)),
                ('peut_vendre', models.BooleanField(default=False)),
                ('peut_encaisser', models.BooleanField(default=False)),
                ('peut_ouvrir_caisse', models.BooleanField(default=False)),
                ('peut_fermer_caisse', models.BooleanField(default=False)),
                ('peut_annuler_vente', models.BooleanField(default=False)),
                ('peut_accorder_remise', models.BooleanField(default=False)),
                ('peut_consulter_rapports', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_points_vente', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Affectation point de vente',
                'verbose_name_plural': 'Affectations points de vente',
            },
        ),
    ]
