# Generated by Django 5.2.13 on 2026-05-07 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('stock', '0001_initial'),
        ('tresorerie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menumodel'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.recettemodel'),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='caisse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_vente_associe', to='tresorerie.caisse'),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_pos', to='tresorerie.caisse'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='fermee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_fermees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='ouverte_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_ouvertes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_pos', to='tresorerie.caisse'),
        ),
        migrations.AddField(
            model_name='vente',
            name='encaisse_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='point_vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='pos.pointvente'),
        ),
        migrations.AddField(
            model_name='vente',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.tablemodel'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pos.vente'),
        ),
    ]
