# Generated by Django 5.2.11 on 2026-07-24 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('hotel', '0001_initial'),
        ('pos', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('rh', '0001_initial'),
        ('stock', '0001_initial'),
        ('tresorerie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caissepointvente',
            name='caisse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='affectation_pos', to='tresorerie.caisse'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='clients.client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.employe'),
        ),
        migrations.AddField(
            model_name='commande',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='stock.entrepot'),
        ),
        migrations.AddField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.tablemodel'),
        ),
        migrations.AddField(
            model_name='comptagesession',
            name='compte_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptages_effectues', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pos.commande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menumodel'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.produit'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.recettemodel'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.unitemodel'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menumodel'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.produit'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.recettemodel'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='pos.commande'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.livreur'),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_vente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='point_vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='pos.pointvente'),
        ),
        migrations.AddField(
            model_name='caissepointvente',
            name='point_vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisses_affectees', to='pos.pointvente'),
        ),
        migrations.AddField(
            model_name='affectationpointvente',
            name='point_vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_employes', to='pos.pointvente'),
        ),
        migrations.AddField(
            model_name='pointventeentrepot',
            name='entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_vente_autorises', to='stock.entrepot'),
        ),
        migrations.AddField(
            model_name='pointventeentrepot',
            name='point_vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots_autorises', to='pos.pointvente'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_pos', to='tresorerie.caisse'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caissier_fermeture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_fermees', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caissier_ouverture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_ouvertes', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='ferme_par_raf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_fermees_raf', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='point_vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pos.pointvente'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='transfert_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tresorerie.transfertcaisse'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_validees', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='comptagesession',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comptage', to='pos.sessioncaisse'),
        ),
        migrations.AddField(
            model_name='shiftemploye',
            name='affectation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='pos.affectationpointvente'),
        ),
        migrations.AddField(
            model_name='shiftemploye',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftemploye',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='pos.shiftemploye'),
        ),
        migrations.AddField(
            model_name='vente',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_pos', to='tresorerie.caisse'),
        ),
        migrations.AddField(
            model_name='vente',
            name='caissier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_effectuees', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_pos', to='clients.client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='encaisse_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_encaissees', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='vente',
            name='point_vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='pos.pointvente'),
        ),
        migrations.AddField(
            model_name='vente',
            name='serveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_servies', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='vente',
            name='session_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='pos.sessioncaisse'),
        ),
        migrations.AddField(
            model_name='vente',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.tablemodel'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pos.vente'),
        ),
        migrations.AddField(
            model_name='commande',
            name='vente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande', to='pos.vente'),
        ),
        migrations.AlterUniqueTogether(
            name='caissepointvente',
            unique_together={('point_vente', 'caisse')},
        ),
        migrations.AlterUniqueTogether(
            name='affectationpointvente',
            unique_together={('employe', 'point_vente', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='pointventeentrepot',
            unique_together={('point_vente', 'entrepot')},
        ),
        migrations.AddConstraint(
            model_name='sessioncaisse',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['OUVERTE', 'EN_COMPTAGE'])), fields=('caisse',), name='unique_session_active_par_caisse'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='pos_command_statut_35ac3b_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['point_vente', 'statut'], name='pos_command_point_v_9ee764_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['numero'], name='pos_command_numero_a01208_idx'),
        ),
    ]
