# Generated by Django 5.2.11 on 2026-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessioncaisse',
            old_name='caissier_fermeture',
            new_name='fermee_par',
        ),
        migrations.RenameField(
            model_name='sessioncaisse',
            old_name='caissier_ouverture',
            new_name='ouverte_par',
        ),
        migrations.RemoveField(
            model_name='pointvente',
            name='type_pv',
        ),
        migrations.RemoveField(
            model_name='pointvente',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='date_collecte',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='ferme_par_raf',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='fonds_collectes',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='solde_attendu',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='solde_reel',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='solde_restant',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='transfert_caisse',
        ),
        migrations.AddField(
            model_name='pointvente',
            name='type',
            field=models.CharField(choices=[('RESTAURATION', 'Restauration'), ('BAR', 'Bar'), ('BOUTIQUE', 'Boutique'), ('RECEPTION', 'Réception'), ('ROOM_SERVICE', 'Room service'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30),
        ),
    ]
