# Generated by Django 5.2.13 on 2026-05-09 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_lignevente_created_at_alter_lignevente_produit'),
        ('restaurant', '0002_remove_ventemodel_lignes_and_more'),
        ('rh', '0001_initial'),
        ('tresorerie', '0002_mouvementcaisse_annule_mouvementcaisse_annule_le_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangementCaissier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('raison', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Changement de caissier',
                'verbose_name_plural': 'Changements de caissier',
                'db_table': 'pos_changements_caissier',
                'ordering': ['-date_changement'],
            },
        ),
        migrations.AlterModelOptions(
            name='sessioncaisse',
            options={'ordering': ['-date_ouverture'], 'verbose_name': 'Session de caisse', 'verbose_name_plural': 'Sessions de caisse'},
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='est_fermee',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='fermee_par',
        ),
        migrations.RemoveField(
            model_name='sessioncaisse',
            name='ouverte_par',
        ),
        migrations.AddField(
            model_name='pointvente',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_vente', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caissier_fermeture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_fermees', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caissier_ouverture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_ouvertes', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='debut_prevu',
            field=models.TimeField(blank=True, help_text='Heure de début de service prévue', null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='fin_prevu',
            field=models.TimeField(blank=True, help_text='Heure de fin de service prévue', null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='point_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pos.pointvente'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='statut',
            field=models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée'), ('SUSPENDUE', 'Suspendue'), ('CLOTUREE', 'Clôturée')], default='OUVERTE', max_length=20),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='total_carte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='total_compte_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='total_especes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='total_mobile_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='caissier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_effectuees', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='vente',
            name='session_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='pos.sessioncaisse'),
        ),
        migrations.AlterField(
            model_name='pointvente',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_vente_associe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessioncaisse',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sessioncaisse',
            name='solde_attendu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sessioncaisse',
            name='solde_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sessioncaisse',
            name='solde_reel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='encaisse_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_encaissees', to='rh.employe'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['session_caisse'], name='pos_ventes_session_f3a8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['caissier'], name='pos_ventes_caissie_06c648_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['encaisse_par'], name='pos_ventes_encaiss_5d8e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['created_at'], name='pos_ventes_created_019695_idx'),
        ),
        migrations.AddField(
            model_name='changementcaissier',
            name='ancien_caissier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changements_sortie', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='changementcaissier',
            name='nouveau_caissier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changements_entree', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='changementcaissier',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changements', to='pos.sessioncaisse'),
        ),
    ]
