# Generated by Django 5.2.11 on 2026-07-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_rename_caissier_fermeture_sessioncaisse_fermee_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='cout_revient',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût unitaire figé au moment de la vente', max_digits=10),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='marge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bénéfice généré par cette ligne (Prix de vente - Coût de revient) * Quantité', max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='cout_revient_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût total des articles vendus', max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='marge_totale',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bénéfice net (montant_total - cout_revient_total)', max_digits=10),
        ),
    ]
