# Generated by Django 5.2.11 on 2026-07-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_lignevente_cout_revient_lignevente_marge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_taxe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somme des prix catalogue', max_digits=10),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='montant_remise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la remise accordée sur cette ligne', max_digits=10),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='prix_catalogue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix sans remise', max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_taxe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somme des prix catalogue', max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant net à payer (sous_total - remise + taxe + livraison)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix net après remise', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque'), ('CREDIT', 'Crédit'), ('SOLDE', 'Solde client'), ('COMPTE_CLIENT', 'Compte client'), ('FACTURE', 'Facture')], default='ESPECES', help_text='Mode principal, utiliser PaiementVente pour les multi-paiements', max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant net à payer (sous_total - remise + taxe)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20),
        ),
    ]
