# Generated by Django 5.2.13 on 2026-05-10 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_changementcaissier_alter_sessioncaisse_options_and_more'),
        ('stock', '0004_inventaire_ligneinventaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvente',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_vente', to='stock.entrepot'),
        ),
    ]
