# Generated by Django 5.2.13 on 2026-05-18 23:42

import apps.pos.models.commande
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_pointvente_entrepot'),
        ('restaurant', '0003_alter_production_options_and_more'),
        ('rh', '0001_initial'),
        ('stock', '0004_inventaire_ligneinventaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=apps.pos.models.commande.generate_commande_numero, max_length=20, unique=True)),
                ('type_commande', models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('EMPORTER', 'À emporter'), ('LIVRAISON', 'Livraison')], default='SUR_PLACE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('SERVIE', 'Servie'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('client_nom', models.CharField(blank=True, max_length=200)),
                ('client_telephone', models.CharField(blank=True, max_length=20)),
                ('adresse_livraison', models.TextField(blank=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_preparation', models.DateTimeField(blank=True, null=True)),
                ('date_service', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.employe')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='pos.pointvente')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.tablemodel')),
                ('vente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande', to='pos.vente')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'pos_commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pos.commande')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menumodel')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.produit')),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.recettemodel')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'pos_lignes_commande',
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='pos_command_statut_35ac3b_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['point_vente', 'statut'], name='pos_command_point_v_9ee764_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['numero'], name='pos_command_numero_a01208_idx'),
        ),
    ]
