# Generated by Django 6.0.5 on 2026-05-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_delete_clientmodel_and_more'),
        ('pos', '0007_ajout_statut_en_cours_de_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='clients.client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='clients.client'),
        ),
    ]
