# Generated by Django 6.0.5 on 2026-05-31 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_commande_client_vente_client'),
        ('rh', '0004_alter_employe_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('EFFECTUE', 'Effectué')], default='PLANIFIE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_planifiees', to='rh.employe')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='pos.pointvente')),
            ],
            options={
                'verbose_name': 'Planning session',
                'verbose_name_plural': 'Plannings sessions',
                'db_table': 'pos_planning_sessions',
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
