# Generated by Django 6.0.5 on 2026-05-31 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_sessionplanning'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncaisse',
            name='depot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant déposé/retiré à la clôture', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='pos.sessionplanning'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='solde_restant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solde laissé dans la caisse après clôture', max_digits=12, null=True),
        ),
    ]
