# Generated by Django 6.0.5 on 2026-06-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_locationmodel_client_delete_clientmodel'),
        ('pos', '0010_sessioncaisse_depot_sessioncaisse_planning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='heures',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.unitemodel'),
        ),
    ]
