# Generated by Django 6.0.5 on 2026-06-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_livreur_commande_frais_livraison_livraison'),
        ('stock', '0014_seed_brasserie_entrepot_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvente',
            name='emplacement',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant principal'), ('BAR', 'Bar piscine'), ('VIP', 'VIP Lounge'), ('TERRASSE', 'Terrasse'), ('RECEPTION', 'Réception hôtel'), ('ROOM_SERVICE', 'Room service'), ('GUICHET', 'Guichet unique')], max_length=20),
        ),
        migrations.CreateModel(
            name='PointVenteEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_vente_autorises', to='stock.entrepot')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots_autorises', to='pos.pointvente')),
            ],
            options={
                'verbose_name': 'Liaison point de vente ↔ entrepôt',
                'verbose_name_plural': 'Liaisons points de vente ↔ entrepôts',
                'db_table': 'pos_point_vente_entrepots',
                'unique_together': {('point_vente', 'entrepot')},
            },
        ),
    ]
