# Generated by Django 5.0.14 on 2026-06-28 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_setup_raf_employe'),
        ('rh', '0007_employe_photo'),
        ('tresorerie', '0011_fix_plages_guichet_et_nettoyage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncaisse',
            name='ferme_par_raf',
            field=models.ForeignKey(blank=True, help_text='RAF qui a validé la collecte et fermeture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_fermees_raf', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='ouvert_par_raf',
            field=models.BooleanField(default=False, help_text='Ouverte avec dépôt RAF depuis la centrale'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='transfert_caisse',
            field=models.ForeignKey(blank=True, help_text='Transfert généré à la collecte (PV → Centrale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_source', to='tresorerie.transfertcaisse'),
        ),
    ]
