# Generated by Django 5.0.14 on 2026-06-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_sessioncaisse_ferme_par_raf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncaisse',
            name='date_collecte',
            field=models.DateTimeField(blank=True, help_text='Quand le RAF a collecté les fonds', null=True),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='fonds_collectes',
            field=models.BooleanField(default=False, help_text='Les fonds ont été transférés à la caisse centrale'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='solde_initial_raf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solde initial déclaré/modifié par le RAF après ouverture', max_digits=12, null=True),
        ),
    ]
