# Generated by Django 5.0.14 on 2026-07-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_sessioncaisse_date_collecte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_COURS_DE_LIVRAISON', 'En cours de livraison'), ('SERVIE', 'Servie'), ('LIVREE', 'Livrée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30),
        ),
    ]
