# Generated by Django 5.0.14 on 2026-07-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_add_payee_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque'), ('CREDIT', 'Crédit'), ('SOLDE', 'Solde client'), ('COMPTE_CLIENT', 'Compte client (hôtel)'), ('FACTURE', 'Facture globale')], default='ESPECES', max_length=20),
        ),
    ]
