# Generated by Django 5.2.11 on 2026-07-10 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_add_credit_solde_mode_paiement_vente'),
        ('stock', '0019_alter_mouvementstock_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='stock.entrepot'),
        ),
    ]
