# Generated by Django 5.2.13 on 2026-07-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_commande_entrepot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifierLoopLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(default='session_verifier', max_length=50, unique=True)),
                ('detenteur', models.CharField(blank=True, help_text='hostname:pid du worker qui detient le verrou', max_length=200)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Verrou boucle de verification',
                'verbose_name_plural': 'Verrous boucle de verification',
                'db_table': 'pos_verifier_loop_lock',
            },
        ),
    ]
