# Generated by Django 5.2.11 on 2026-07-24 09:53

import apps.hotel.models.location
import apps.hotel.models.reservations
import apps.hotel.models.sejours
import apps.hotel.models.unite
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('entreprises', '0001_initial'),
        ('facturation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('unite_facturation', models.CharField(choices=[('HEURE', 'Heure'), ('DEMI_JOURNEE', 'Demi-journée'), ('JOURNEE', 'Journée'), ('NUITEE', 'Nuitée'), ('SEMAINE', 'Semaine'), ('MOIS', 'Mois'), ('FORFAIT', 'Forfait')], max_length=30)),
                ('duree_minutes', models.PositiveIntegerField(blank=True, help_text='Durée de référence en minutes (ex: 60 pour heure, 1440 pour journée)', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Type de tarif',
                'verbose_name_plural': 'Types de tarifs',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PlanTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('type_client', models.CharField(choices=[('TOUS', 'Tous les clients'), ('PARTICULIER', 'Particulier'), ('ENTREPRISE', 'Entreprise'), ('AGENCE', 'Agence'), ('ADMINISTRATION', 'Administration')], default='TOUS', max_length=30)),
                ('remboursable', models.BooleanField(default=True)),
                ('petit_dejeuner_inclus', models.BooleanField(default=False)),
                ('taxes_incluses', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('priorite', models.PositiveSmallIntegerField(default=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_tarifaires', to='entreprises.etablissement')),
            ],
            options={
                'verbose_name': 'Plan tarifaire',
                'verbose_name_plural': 'Plans tarifaires',
                'ordering': ['priorite', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.hotel.models.reservations.generate_reservation_code, editable=False, max_length=50, unique=True)),
                ('date_arrivee_prevue', models.DateTimeField()),
                ('date_depart_prevue', models.DateTimeField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('OPTION', 'Option'), ('CONFIRMEE', 'Confirmée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('ANNULEE', 'Annulée'), ('NO_SHOW', 'Client non présenté'), ('TRANSFORMEE', 'Transformée en séjour')], default='CONFIRMEE', max_length=30)),
                ('nombre_adultes', models.PositiveSmallIntegerField(default=1)),
                ('nombre_enfants', models.PositiveSmallIntegerField(default=0)),
                ('montant_acompte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total_estime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('annule_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_annulees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='clients.client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_crees', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='entreprises.etablissement')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_arrivee_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.hotel.models.sejours.generate_sejour_code, editable=False, max_length=50, unique=True)),
                ('date_arrivee', models.DateTimeField()),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('CHECK_IN', 'Check-in effectué'), ('EN_COURS', 'En cours'), ('PROLONGE', 'Prolongé'), ('CHECK_OUT', 'Check-out effectué'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=30)),
                ('nombre_adultes', models.PositiveSmallIntegerField(default=1)),
                ('nombre_enfants', models.PositiveSmallIntegerField(default=0)),
                ('montant_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_supplements', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sejours', to='clients.client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sejours_crees', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sejours', to='entreprises.etablissement')),
                ('ferme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sejours_fermes', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sejours', to='hotel.reservation')),
            ],
            options={
                'verbose_name': 'Séjour',
                'verbose_name_plural': 'Séjours',
                'ordering': ['-date_arrivee'],
            },
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('type_piece', models.CharField(blank=True, max_length=50)),
                ('numero_piece', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('est_principal', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('sejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='hotel.sejour')),
            ],
            options={
                'verbose_name': 'Occupant',
                'verbose_name_plural': 'Occupants',
            },
        ),
        migrations.CreateModel(
            name='ServiceSejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_sejour', to='facturation.facturemodel')),
                ('sejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotel.sejour')),
            ],
            options={
                'verbose_name': 'Service du séjour',
                'verbose_name_plural': 'Services du séjour',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('CHAMBRE', 'Chambre'), ('VIP', 'VIP'), ('SALLE', 'Salle'), ('ESPACE', 'Espace'), ('ESPACE_BAR', 'Espace + Bar'), ('BAR', 'Bar VIP'), ('SUITE', 'Suite'), ('STUDIO', 'Studio'), ('APPARTEMENT', 'Appartement'), ('DORTOIR', 'Dortoir')], default='CHAMBRE', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('capacite_par_defaut', models.PositiveSmallIntegerField(default=1)),
                ('surface_par_defaut_m2', models.FloatField(blank=True, null=True)),
                ('couleur', models.CharField(blank=True, help_text="Code couleur pour l'affichage", max_length=20)),
                ('icone', models.CharField(blank=True, help_text="Icône pour l'affichage", max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_chambres', to='entreprises.etablissement')),
            ],
            options={
                'verbose_name': 'Type de chambre',
                'verbose_name_plural': 'Types de chambres',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TarifChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('nombre_personnes_incluses', models.PositiveSmallIntegerField(default=1)),
                ('supplement_adulte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplement_enfant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('jours_semaine', models.JSONField(blank=True, default=list, help_text='Exemple : [0, 1, 2, 3, 4] pour lundi à vendredi.')),
                ('quantite_minimale', models.PositiveIntegerField(default=1)),
                ('quantite_maximale', models.PositiveIntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_chambres', to='entreprises.etablissement')),
                ('plan_tarifaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='hotel.plantarifaire')),
                ('type_chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='hotel.typechambre')),
                ('type_tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_chambres', to='hotel.typetarif')),
            ],
            options={
                'verbose_name': 'Tarif de chambre',
                'verbose_name_plural': 'Tarifs des chambres',
                'ordering': ['type_chambre', 'plan_tarifaire', 'type_tarif', 'montant'],
            },
        ),
        migrations.CreateModel(
            name='CreneauTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
                ('type_tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='hotel.typetarif')),
            ],
            options={
                'verbose_name': 'Créneau tarifaire',
                'verbose_name_plural': 'Créneaux tarifaires',
            },
        ),
        migrations.CreateModel(
            name='UniteModel',
            fields=[
                ('id', models.CharField(default=apps.hotel.models.unite.generate_unite_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_unite', models.CharField(choices=[('CHAMBRE', 'Chambre'), ('VIP', 'VIP'), ('SALLE', 'Salle'), ('ESPACE', 'Espace'), ('ESPACE_BAR', 'Espace + Bar'), ('BAR', 'Bar VIP')], default='CHAMBRE', max_length=20)),
                ('capacite', models.IntegerField(default=1)),
                ('surface_m2', models.FloatField(blank=True, null=True)),
                ('equipements', models.JSONField(default=list)),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix par heure', max_digits=10)),
                ('prix_jour', models.DecimalField(decimal_places=2, default=0, help_text='Prix par jour', max_digits=10)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVEE', 'Réservée'), ('OCCUPEE', 'Occupée'), ('A_NETTOYER', 'À nettoyer'), ('NETTOYAGE', 'Nettoyage en cours'), ('A_INSPECTER', 'À inspecter'), ('MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel/unites/')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='hotel.typechambre')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'db_table': 'hotel_unites',
                'ordering': ['type_unite', 'code'],
            },
        ),
        migrations.AddField(
            model_name='sejour',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sejours', to='hotel.unitemodel'),
        ),
        migrations.CreateModel(
            name='ReservationChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tarif_nom', models.CharField(max_length=100)),
                ('plan_tarifaire_nom', models.CharField(max_length=150)),
                ('montant_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres_reservees', to='hotel.reservation')),
                ('tarif_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hotel.tarifchambre')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hotel.unitemodel')),
            ],
            options={
                'verbose_name': 'Chambre réservée',
                'verbose_name_plural': 'Chambres réservées',
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.CharField(default=apps.hotel.models.location.generate_location_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type_location', models.CharField(choices=[('CHAMBRE', 'Location chambre'), ('SALLE', 'Location salle'), ('ESPACE', "Location d'espace"), ('ESPACE_BAR', 'Location espace + bar'), ('BAR', 'Location bar VIP')], default='CHAMBRE', max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('type_tarif', models.CharField(choices=[('HEURE', 'Par heure'), ('JOUR', 'Par jour')], default='HEURE', max_length=10)),
                ('montant_avance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('CONFIRMEE', 'Confirmée'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='CONFIRMEE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client_nom', models.CharField(blank=True, default='', max_length=200)),
                ('client_telephone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='clients.client')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='hotel.unitemodel')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'hotel_locations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='hotel.unitemodel')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques des statuts',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='plantarifaire',
            constraint=models.UniqueConstraint(fields=('etablissement', 'code'), name='unique_plan_tarifaire_etablissement'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['client', 'statut'], name='hotel_reser_client__19da68_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date_arrivee_prevue', 'statut'], name='hotel_reser_date_ar_66e64f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['etablissement', 'statut'], name='hotel_reser_etablis_b211ec_idx'),
        ),
        migrations.AddIndex(
            model_name='sejour',
            index=models.Index(fields=['client', 'statut'], name='hotel_sejou_client__808ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='sejour',
            index=models.Index(fields=['chambre', 'date_arrivee'], name='hotel_sejou_chambre_f6d3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='sejour',
            index=models.Index(fields=['statut'], name='hotel_sejou_statut_9e729a_idx'),
        ),
        migrations.AddIndex(
            model_name='locationmodel',
            index=models.Index(fields=['client', 'statut'], name='hotel_locat_client__ae3c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='locationmodel',
            index=models.Index(fields=['unite', 'date_debut'], name='hotel_locat_unite_i_b0b2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='locationmodel',
            index=models.Index(fields=['type_location', 'statut'], name='hotel_locat_type_lo_4e19da_idx'),
        ),
    ]
