# Generated by Django 5.2.13 on 2026-05-17 20:14

import apps.hotel.models.client
import apps.hotel.models.location
import apps.hotel.models.unite
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.CharField(default=apps.hotel.models.client.generate_client_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('piece_identite', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_piece', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'hotel_clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='UniteModel',
            fields=[
                ('id', models.CharField(default=apps.hotel.models.unite.generate_unite_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_unite', models.CharField(choices=[('CHAMBRE', 'Chambre'), ('SALLE', 'Salle'), ('JARDIN', 'Jardin'), ('COUR', 'Cour'), ('VIP', 'Espace VIP'), ('TERRASSE', 'Terrasse'), ('AUTRE', 'Autre')], default='CHAMBRE', max_length=20)),
                ('capacite', models.IntegerField(default=1)),
                ('surface_m2', models.FloatField(blank=True, null=True)),
                ('equipements', models.JSONField(default=list)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_type', models.CharField(choices=[('NUIT', 'Par nuit'), ('HEURE', 'Par heure'), ('JOUR', 'Par jour'), ('FORFAIT', 'Forfait')], default='NUIT', max_length=20)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPEE', 'Occupée'), ('RESERVEE', 'Réservée'), ('NETTOYAGE', 'Nettoyage'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'db_table': 'hotel_unites',
                'ordering': ['type_unite', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.CharField(default=apps.hotel.models.location.generate_location_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type_location', models.CharField(choices=[('SEJOUR', 'Séjour'), ('EVENEMENT', 'Événement')], default='SEJOUR', max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('nombre_personnes', models.IntegerField(default=1)),
                ('motif', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('CONFIRMEE', 'Confirmée'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='hotel.clientmodel')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='hotel.unitemodel')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'hotel_locations',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['client', 'statut'], name='hotel_locat_client__ae3c5f_idx'), models.Index(fields=['unite', 'date_debut'], name='hotel_locat_unite_i_b0b2f8_idx'), models.Index(fields=['type_location', 'statut'], name='hotel_locat_type_lo_4e19da_idx')],
            },
        ),
    ]
