# Generated by Django 5.2.11 on 2026-07-25 12:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plantarifaire',
            name='unique_plan_tarifaire_etablissement',
        ),
        migrations.RemoveField(
            model_name='plantarifaire',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='tarifchambre',
            name='plan_tarifaire',
        ),
        migrations.RemoveField(
            model_name='tarifchambre',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='tarifchambre',
            name='type_chambre',
        ),
        migrations.RemoveField(
            model_name='tarifchambre',
            name='type_tarif',
        ),
        migrations.RenameField(
            model_name='reservationchambre',
            old_name='type_tarif_nom',
            new_name='tarif_nom',
        ),
        migrations.RemoveField(
            model_name='reservationchambre',
            name='plan_tarifaire_nom',
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Nuitée, Sieste, Mensuel', max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='hotel.unitemodel')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'ordering': ['montant'],
            },
        ),
        migrations.AlterField(
            model_name='reservationchambre',
            name='tarif_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hotel.tarif'),
        ),
        migrations.DeleteModel(
            name='CreneauTarifaire',
        ),
        migrations.DeleteModel(
            name='PlanTarifaire',
        ),
        migrations.DeleteModel(
            name='TypeTarif',
        ),
        migrations.DeleteModel(
            name='TarifChambre',
        ),
    ]
