# Generated by Django 5.2.13 on 2026-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_repair_client_table_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitemodel',
            options={'ordering': ['type_unite', 'code'], 'verbose_name': 'Chambre', 'verbose_name_plural': 'Chambres'},
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='contact_nom',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='contact_telephone',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='montant_paye',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='unitemodel',
            name='prix_type',
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='type_location',
            field=models.CharField(choices=[('CHAMBRE', 'Location chambre'), ('ESPACE', "Location d'espace"), ('BAR', 'Location bar VIP')], default='CHAMBRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='unitemodel',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Prix par heure', max_digits=10),
        ),
        migrations.AlterField(
            model_name='unitemodel',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPEE', 'Occupée'), ('NETTOYAGE', 'Nettoyage'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='unitemodel',
            name='type_unite',
            field=models.CharField(choices=[('CHAMBRE', 'Chambre'), ('VIP', 'VIP'), ('ESPACE', 'Espace'), ('BAR', 'Bar VIP')], default='CHAMBRE', max_length=20),
        ),
    ]
