# Generated by Django 5.2.13 on 2026-05-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_v2_chambres_hourly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='type_location',
            field=models.CharField(choices=[('CHAMBRE', 'Location chambre'), ('SALLE', 'Location salle'), ('ESPACE', "Location d'espace"), ('ESPACE_BAR', 'Location espace + bar'), ('BAR', 'Location bar VIP')], default='CHAMBRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='unitemodel',
            name='type_unite',
            field=models.CharField(choices=[('CHAMBRE', 'Chambre'), ('VIP', 'VIP'), ('SALLE', 'Salle'), ('ESPACE', 'Espace'), ('ESPACE_BAR', 'Espace + Bar'), ('BAR', 'Bar VIP')], default='CHAMBRE', max_length=20),
        ),
    ]
