# Generated by Django 6.0.5 on 2026-05-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_delete_clientmodel_and_more'),
        ('hotel', '0005_ajout_commande_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='clients.client'),
        ),
        migrations.DeleteModel(
            name='ClientModel',
        ),
    ]
