# Generated by Django 5.2.13 on 2026-06-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_locationmodel_client_delete_clientmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/unites/'),
        ),
    ]
