# Generated by Django 6.0.5 on 2026-06-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_unitemodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='nombre_personnes',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='options',
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='client_nom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='client_telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='montant_avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='statut',
            field=models.CharField(choices=[('CONFIRMEE', 'Confirmée'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='CONFIRMEE', max_length=20),
        ),
    ]
