# Generated by Django 5.2.13 on 2026-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_locationmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='type_tarif',
            field=models.CharField(choices=[('HEURE', 'Par heure'), ('JOUR', 'Par jour')], default='HEURE', max_length=10),
        ),
        migrations.AddField(
            model_name='unitemodel',
            name='prix_jour',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix par jour', max_digits=10),
        ),
    ]
