# Generated by Django 5.2.11 on 2026-07-23 23:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('hotel', '0009_locationmodel_type_tarif_unitemodel_prix_jour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('unite_facturation', models.CharField(choices=[('HEURE', 'Heure'), ('DEMI_JOURNEE', 'Demi-journée'), ('JOURNEE', 'Journée'), ('NUITEE', 'Nuitée'), ('SEMAINE', 'Semaine'), ('MOIS', 'Mois'), ('FORFAIT', 'Forfait')], max_length=30)),
                ('duree_minutes', models.PositiveIntegerField(blank=True, help_text='Durée de référence en minutes (ex: 60 pour heure, 1440 pour journée)', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Type de tarif',
                'verbose_name_plural': 'Types de tarifs',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterField(
            model_name='unitemodel',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVEE', 'Réservée'), ('OCCUPEE', 'Occupée'), ('A_NETTOYER', 'À nettoyer'), ('NETTOYAGE', 'Nettoyage en cours'), ('A_INSPECTER', 'À inspecter'), ('MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20),
        ),
        migrations.CreateModel(
            name='PlanTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('type_client', models.CharField(choices=[('TOUS', 'Tous les clients'), ('PARTICULIER', 'Particulier'), ('ENTREPRISE', 'Entreprise'), ('AGENCE', 'Agence'), ('ADMINISTRATION', 'Administration')], default='TOUS', max_length=30)),
                ('remboursable', models.BooleanField(default=True)),
                ('petit_dejeuner_inclus', models.BooleanField(default=False)),
                ('taxes_incluses', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('priorite', models.PositiveSmallIntegerField(default=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_tarifaires', to='entreprises.etablissement')),
            ],
            options={
                'verbose_name': 'Plan tarifaire',
                'verbose_name_plural': 'Plans tarifaires',
                'ordering': ['priorite', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('CHAMBRE', 'Chambre'), ('VIP', 'VIP'), ('SALLE', 'Salle'), ('ESPACE', 'Espace'), ('ESPACE_BAR', 'Espace + Bar'), ('BAR', 'Bar VIP'), ('SUITE', 'Suite'), ('STUDIO', 'Studio'), ('APPARTEMENT', 'Appartement'), ('DORTOIR', 'Dortoir')], default='CHAMBRE', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('capacite_par_defaut', models.PositiveSmallIntegerField(default=1)),
                ('surface_par_defaut_m2', models.FloatField(blank=True, null=True)),
                ('couleur', models.CharField(blank=True, help_text="Code couleur pour l'affichage", max_length=20)),
                ('icone', models.CharField(blank=True, help_text="Icône pour l'affichage", max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_chambres', to='entreprises.etablissement')),
            ],
            options={
                'verbose_name': 'Type de chambre',
                'verbose_name_plural': 'Types de chambres',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='unitemodel',
            name='type_chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='hotel.typechambre'),
        ),
        migrations.CreateModel(
            name='TarifChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('nombre_personnes_incluses', models.PositiveSmallIntegerField(default=1)),
                ('supplement_adulte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplement_enfant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('jours_semaine', models.JSONField(blank=True, default=list, help_text='Exemple : [0, 1, 2, 3, 4] pour lundi à vendredi.')),
                ('quantite_minimale', models.PositiveIntegerField(default=1)),
                ('quantite_maximale', models.PositiveIntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_chambres', to='entreprises.etablissement')),
                ('plan_tarifaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='hotel.plantarifaire')),
                ('type_chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='hotel.typechambre')),
                ('type_tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_chambres', to='hotel.typetarif')),
            ],
            options={
                'verbose_name': 'Tarif de chambre',
                'verbose_name_plural': 'Tarifs des chambres',
                'ordering': ['type_chambre', 'plan_tarifaire', 'type_tarif', 'montant'],
            },
        ),
        migrations.CreateModel(
            name='CreneauTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
                ('type_tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='hotel.typetarif')),
            ],
            options={
                'verbose_name': 'Créneau tarifaire',
                'verbose_name_plural': 'Créneaux tarifaires',
            },
        ),
        migrations.AddConstraint(
            model_name='plantarifaire',
            constraint=models.UniqueConstraint(fields=('etablissement', 'code'), name='unique_plan_tarifaire_etablissement'),
        ),
    ]
