# Generated by Django 5.2.11 on 2026-07-23 23:23

import apps.hotel.models.reservations
import apps.hotel.models.sejours
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_credit_plafond'),
        ('entreprises', '0001_initial'),
        ('facturation', '0006_facturemodel_bon_entree_facturemodel_fournisseur_and_more'),
        ('hotel', '0010_typetarif_alter_unitemodel_statut_plantarifaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStatutChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='hotel.unitemodel')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques des statuts',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.hotel.models.reservations.generate_reservation_code, editable=False, max_length=50, unique=True)),
                ('date_arrivee_prevue', models.DateTimeField()),
                ('date_depart_prevue', models.DateTimeField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('OPTION', 'Option'), ('CONFIRMEE', 'Confirmée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('ANNULEE', 'Annulée'), ('NO_SHOW', 'Client non présenté'), ('TRANSFORMEE', 'Transformée en séjour')], default='CONFIRMEE', max_length=30)),
                ('nombre_adultes', models.PositiveSmallIntegerField(default=1)),
                ('nombre_enfants', models.PositiveSmallIntegerField(default=0)),
                ('montant_acompte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total_estime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('annule_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_annulees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='clients.client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_crees', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='entreprises.etablissement')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_arrivee_prevue'],
            },
        ),
        migrations.CreateModel(
            name='ReservationChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tarif_nom', models.CharField(max_length=100)),
                ('plan_tarifaire_nom', models.CharField(max_length=150)),
                ('montant_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hotel.unitemodel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres_reservees', to='hotel.reservation')),
                ('tarif_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hotel.tarifchambre')),
            ],
            options={
                'verbose_name': 'Chambre réservée',
                'verbose_name_plural': 'Chambres réservées',
            },
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.hotel.models.sejours.generate_sejour_code, editable=False, max_length=50, unique=True)),
                ('date_arrivee', models.DateTimeField()),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('CHECK_IN', 'Check-in effectué'), ('EN_COURS', 'En cours'), ('PROLONGE', 'Prolongé'), ('CHECK_OUT', 'Check-out effectué'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=30)),
                ('nombre_adultes', models.PositiveSmallIntegerField(default=1)),
                ('nombre_enfants', models.PositiveSmallIntegerField(default=0)),
                ('montant_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_supplements', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sejours', to='hotel.unitemodel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sejours', to='clients.client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sejours_crees', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sejours', to='entreprises.etablissement')),
                ('ferme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sejours_fermes', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sejours', to='hotel.reservation')),
            ],
            options={
                'verbose_name': 'Séjour',
                'verbose_name_plural': 'Séjours',
                'ordering': ['-date_arrivee'],
            },
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('type_piece', models.CharField(blank=True, max_length=50)),
                ('numero_piece', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('est_principal', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('sejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='hotel.sejour')),
            ],
            options={
                'verbose_name': 'Occupant',
                'verbose_name_plural': 'Occupants',
            },
        ),
        migrations.CreateModel(
            name='ServiceSejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_sejour', to='facturation.facturemodel')),
                ('sejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotel.sejour')),
            ],
            options={
                'verbose_name': 'Service du séjour',
                'verbose_name_plural': 'Services du séjour',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['client', 'statut'], name='hotel_reser_client__19da68_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date_arrivee_prevue', 'statut'], name='hotel_reser_date_ar_66e64f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['etablissement', 'statut'], name='hotel_reser_etablis_b211ec_idx'),
        ),
        migrations.AddIndex(
            model_name='sejour',
            index=models.Index(fields=['client', 'statut'], name='hotel_sejou_client__808ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='sejour',
            index=models.Index(fields=['chambre', 'date_arrivee'], name='hotel_sejou_chambre_f6d3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='sejour',
            index=models.Index(fields=['statut'], name='hotel_sejou_statut_9e729a_idx'),
        ),
    ]
